### ISSUE TITLE
featured_image size

### ISSUE THREAD

**Issue by jhr2267** [theNewDynamic/gohugo-theme-ananke#100]
Excuse me if this is a noob question, but how do I change the size of the feature_image that is displayed?  Mine is cropped from the bottom so that it is significantly narrower than this example [https://gohugo-ananke-theme-demo.netlify.com/ ](url)

Which files should I change?  Perhaps the image size could be made into an easy to change variable.

**Comment by corch** [comment]
I have been trying to figure this out as well. The file "/layouts/partials/site-header.html" is where the image is included in the page but I don't know if this is the right place to change it, or what css should be used to affect the height of the image. 

I'm also having a problem with the description parameter set in config.toml not displaying on the header image below the site title... not sure if its related though

**Comment by qidai628** [comment]
What's the difference between "/layouts/partials/site-header.html" and "/layouts/partials/page-header.html"? I added "omit_header_text = true" in "_index.md", but failed to omit the title and description on front page's background image. Then I removed the h1&h2 html code segment in "/layouts/partials/site-header.html", however the background image was cut off from bottom.
