### ISSUE TITLE
Adding custom element under the headline

### ISSUE THREAD

**Issue by lukylab** [theNewDynamic/gohugo-theme-ananke#119]
Hi,
The theme is great, thank you a lot, Bud! I just wonder if you could help me – I would like to add the custom element (a Facebook Messenger button) just under the headline on the main image (see attached mockup). Could you please advise if it is possible and how to do it?
Thank you,
Lukáš
![prago](https://user-images.githubusercontent.com/5338092/43731604-4eac0626-99af-11e8-9c32-be7f95391d19.png)

**Comment by budparr** [comment]
Hey, @lukylab - You can duplicate any template in your `layouts` directory and edit it there. 

So, for https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/site-header.html

you'd move it from: `themes/gohugo-theme-ananke/layouts/partials/site-header.html`

to: `layouts/partials/site-header.html`

**Comment by lukylab** [comment]
Thank you, Bud!
