### ISSUE TITLE
Allow custom summaries

### ISSUE THREAD

**Issue by FayeAlephNil** [theNewDynamic/gohugo-theme-ananke#122]
It would be nice if the summary sections checked the page parameters to see if a custom summary was available to use.

**Comment by budparr** [comment]
I think summaries should pick up the `description` field.

**Comment by SeanTAllen** [comment]
I made changes in my usage of this to use the description field.

**Comment by regisphilibert** [comment]
Use `summary` in the front matter.
`.Summary` look for a `summary` front matter and if not proceeds to generate it from content.
