### ISSUE TITLE
Allow multiple sections to be listed under recent

### ISSUE THREAD

**Issue by FayeAlephNil** [theNewDynamic/gohugo-theme-ananke#123]
I'd like to have two sections listed under my home page just like the default "recent posts". Namely a "stories" and "posts" lists. If this would be implemented it would be great!

**Comment by budparr** [comment]
Hey, @Strikingwolf You should be able to set those sections in your config, like this:

```
[params]
mainSections = ["blog", "docs"]
```

**Comment by rspencer01** [comment]
I don't see how that helps.  The relevant lines in the code are

https://github.com/budparr/gohugo-theme-ananke/blob/8c1280c2a3f2fe9b7df4930cb77f48e27735bd21/layouts/index.html#L5-L21

and further.  It seems to pick the first one in the list (see the line `{{ $section_name := index (.Site.Params.mainSections) 0 }}` ) and performs no loops over all the sections.

**Comment by liangzhengyiyi** [comment]
I set the Config with 
[params]
mainSections = ["project", "computation", "article"]

It worked! Now I have three sections listed under "recent posts". **However, I also want to add a headline above each section to be clear and consistent. Right now, there is only one section name "recent posts".** How can I achieve it?  Thanks for your help!!

gohugo-theme-ananke/layouts/index.html codes are as follow:
`  </article>
  {{/* Define a section to pull recent posts from. For Hugo 0.20 this will default to the section with the most number of pages. */}}
  {{ $mainSections := .Site.Params.mainSections | default (slice "post") }}
  {{/* Create a variable with that section to use in multiple places. */}}
  {{ $section := where .Site.RegularPages "Section" "in" $mainSections }}
  {{/* Check to see if the section is defined for ranging through it */}}
  {{ $section_count := len $section }}
  {{ if ge $section_count 1 }}
    {{/* Derive the section name  */}}
    {{ $section_name := index (.Site.Params.mainSections) 0 }}

    <div class="pa3 pa4-ns w-100 w-70-ns center">
      {{/* Use $section_name to get the section title. Use "with" to only show it if it exists */}}
       {{ with .Site.GetPage "section" $section_name }}
          <h1 class="flex-none">
            {{ .Title }}
          </h1>
        {{ end }}
`
