### ISSUE TITLE
Drop down menu items

### ISSUE THREAD

**Issue by Allen616** [theNewDynamic/gohugo-theme-ananke#126]
First off, thanks for a great template, documentation and your responsiveness to questions.

I am trying having difficulty creating drop down (?nested?) menu items for the main menu. For instance on my site [citizenlabs.org,](https://citizenlabs.org/about/) I would like to have a drop down menu from "About" that would go to our Code of Conduct, Sponsors, and Team. 

Find the [github repo here.](https://github.com/citizenlabsgr/homepage)

I have organized these file in the content directory, About.

content
-->[about](https://citizenlabs.org/about/)
------>_index.md
------>[conduct.md](https://citizenlabs.org/about/conduct/)
------>[sponsors.md](https://citizenlabs.org/about/sponsors/)
------>[team.md](https://citizenlabs.org/about/team/)

I have been reviewing and asking questions in the Hugo community and also searching for Hugo templates as examples. Surprisingly I don't see any of the existing templates with drop down navigation menus. I have spent so many hours trying to figure this out, any help would be appreciated.

Thanks

**Comment by valkiii** [comment]
Hi Allen616 I went on your website and it seems that you were able to solve it. Can you tell me how you did it? Thank you

**Comment by kwk** [comment]
@valkiii I think this is the place you're looking for, right @Allen616 ? https://github.com/citizenlabsgr/homepage/blob/7b210347902b9dddba74748851297f8fa4cf4e9c/config.toml#L74
