### ISSUE TITLE
Alignment question

### ISSUE THREAD

**Issue by emin63** [theNewDynamic/gohugo-theme-ananke#158]
I notice that if I put text in my `_index.md` files the text sometimes gets centered instead of left aligned.

It looks like this is because of the following css being applied:

```
   <section class="cf ph3 ph5-l pv3 pv4-l f4 tc-l center measure-wide lh-copy mid-gray">
```

Is there a suggested approach if I do not want text to be centered but instead left aligned? Or should I just drop in some of my own CSS and formatting inside my `_index.md` file?

Thanks.

**Comment by budparr** [comment]
Hey, @emin63 I seemed to have missed this. Sorry for taking so long to reply. The class that makes it centered is `tc-l` so, you can make a copy of the template in your root, and remove that class and it should be good. Let me know if that works for you.

**Comment by plett** [comment]
@budparr I have the same issue and removing `tc-l` from the list of classes resolves it for me. Thanks.

**Comment by can-li1128** [comment]
Hi, is this solution for layouts/_default//list.html? I still have the centered text after removing `tc-1`, but only on a full size window on computer screen, not when window is narrowed or on a phone.  I'd appreciate help figuring this out. Thank you.

**Comment by davidbeckonline** [comment]
Created the file. Issue resolved.
Thank you very much for your help!
