### ISSUE TITLE
robots.txt disallows everything despite "Environment: production"

### ISSUE THREAD

**Issue by labanskoller** [theNewDynamic/gohugo-theme-ananke#201]
I wanted to add `robots.txt` to my site so I added

```
enableRobotsTXT: true
```

to my `config.yaml`. That didn't turn out as expected. It got the following content:

```
User-agent: *
# robotstxt.org - if ENV production variable is false robots will be disallowed.

  Disallow: /

```

On the web server I render my site using just `hugo`. On my workstation I tried with `hugo server --environment=production` but got the same result. The command wrote the environment as I specified it however:

```
$ hugo server --environment=production
...
Environment: "production"
Serving pages from memory
...
```

I'm running Hugo 0.57.2.

After some digging I found that `layouts/robots.txt` in this git is looking for the environment variable `HUGO_ENV` or the configuration variable `params.env` (`Site.Params.env`).

My conclusion is that the Ananke theme got environment support before Hugo did and when Hugo added it in [version 0.53](https://gohugo.io/news/0.53-relnotes/) it was in a slightly different way. Running `hugo server` will set the environment to _development_ and running `hugo` will set it to _production_. It can be overridden by OS environment variable `HUGO_ENVIRONMENT`(note, not `HUGO_ENV`!) or by using the `--environment` option.

My opinion is that the Ananke theme shall support the official way of specifying environment.

**Comment by budparr** [comment]
`HUGO_ENV` is what we use on all of our production sites and it works fine. 

I agree though that we should change `params.env` to Hugo's newer environment setting (though, truth is, we only use `HUGO_ENV` at work and I'm not sure of the value of the second setting (someone else added it to the theme).

**Comment by labanskoller** [comment]
Which version of Hugo are you using? I just upgraded to 0.57.2 and when I set `HUGO_ENV` it's not used. Look at the `Environment:` line:
```
$ HUGO_ENV=production hugo server
Building sites … WARN 2019/08/21 23:55:49 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/08/21 23:55:49 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/08/21 23:55:49 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.

                   | EN  
+------------------+----+
  Pages            | 23  
  Paginator pages  |  0  
  Non-page files   | 37  
  Static files     |  5  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 515 ms
Watching for changes in /home/user/git/labanskoller.se/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /home/user/git/labanskoller.se/config.yaml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Using `HUGO_ENVIRONMENT` however works:
```
 HUGO_ENVIRONMENT=production hugo server
Building sites … WARN 2019/08/21 23:56:55 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/08/21 23:56:55 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/08/21 23:56:55 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.

                   | EN  
+------------------+----+
  Pages            | 23  
  Paginator pages  |  0  
  Non-page files   | 37  
  Static files     |  5  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 521 ms
Watching for changes in /home/user/git/labanskoller.se/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /home/user/git/labanskoller.se/config.yaml
Environment: "production"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by labanskoller** [comment]
I already made a proposal before I read your comment. I'll link a pull request we can discuss.

**Comment by labanskoller** [comment]
Also, please see this message by Bjørn Erik Pedersen about the official support: https://discourse.gohugo.io/t/how-to-serve-different-files-depending-on-environment/16212/2

**Comment by budparr** [comment]
`HUGO_ENV` is for the server, not for Hugo, but Hugo can use it `HUGO_ENV=production hugo serve` and that works fine. Where you have `Environment: "development"` in your build log is Hugo's environment.

As this would be a breaking change for some, we'd have to be careful about changing the other value. Perhaps add it as an additional conditional at first with a warning (we don't really have that for themes though) and swap it outright later.

**Comment by labanskoller** [comment]
I'm not sure I follow what you mean by "server". Do you refer to the server which hosts your site (so a physical server or a VM) and that `HUGO_ENV` is just an environment variable you chose to set on that server so it could be used in the Ananke theme? Or do you refer to Hugo's built-in web server started by `hugo server`?

If the latter I don't see any difference between running `hugo` to template files to the filesystem or `hugo server` to start a web server when it comes to the handling of `HUGO_ENV` and `HUGO_ENVIRONMENT`. `hugo server` is nice enough to tell me which environment is being used so it's easy to check. To test how `hugo` behaves I changed `robots.txt` to use `hugo.Environment` instead as suggested by my pull request.

Since *production* is the default environment when running just `hugo` I tried to change it the other way: to *development*. Running `HUGO_ENV=development hugo` rendered `robots.txt` as `  Disallow:` which is the production configuration but running `HUGO_ENVIRONMENT=development hugo` successfully changed the environment and `robots.txt` was rendered as `  Disallow: /`.

I agree that it's wise to be careful and backwards compatible. Do you think it's OK to skip the support for `Site.Params.env`? I've not seen that anywhere else but I'm new to Hugo and don't know the history.

**Comment by labanskoller** [comment]
> Do you think it's OK to skip the support for Site.Params.env?

Sorry, I think you answered that question already in your first comment:

> I agree though that we should change params.env to Hugo's newer environment setting

**Comment by budparr** [comment]
Yes, `HUGO_ENV` is often used as a setting in deployment. That should not change here. The other value that is now a Param should change to Hugo's env.

**Comment by labanskoller** [comment]
I've added a new commit (03aad29541f74c53dc5df35db29d13888f93b32e) to the pull request. I now try to support both ways. When deciding what CSS classes to add to `<body>` however I feel I need to choose only one way, and I hope you agree that the future is to use Hugo's built-in environment support so I chose that over `HUGO_ENV`. Tell me if you can't accept that. I don't know to what extent those CSS classes are used in the field. Please see the second paragraph in the commit message:

```
   Continue supporting HUGO_ENV
    
    Revert some of the changes done in
    a7324c5f15effe5d2b78992fc7b829b29152a7f9. Continue supporting the
    environment variable "HUGO_ENV" which doesn't affect Hugo while still
    supporting the new, official ways of setting the environment.
    
    <body> will however get a class named by the official environment only
    since it would be confusing to add both a "development" class and a
    "production" class at the same time if the site is rendered using this
    command for instance:
    
      $ HUGO_ENV=production hugo server

    <body> will however get a class named by the official environment only
    since it would be confusing to add both a "development" class and a
    "production" class at the same time if the site is rendered using this
    command for instance:
    
      $ HUGO_ENV=production hugo server
```

**Comment by Bas-Man** [comment]
I would think the code to check production could be changed to
```
{{ if hugo.IsProduction }}
```
I use this on my site, which I have just started. I use this because I am using a github workflow to deploy. Its not convenient to pass HUGO_ENV to the hugo command and the template ignore the -e option.

**Comment by zar3bski** [comment]
About **robots.txt**, I was surprised by the fact that `HUGO_ENV production` produced
```
User-agent: *
Disallow:
```
instead of [what seems to be expected for indexing to occur](https://developers.google.com/search/docs/advanced/robots/create-robots-txt?hl=en)
```
User-agent: *
Allow: /

Sitemap: http://www.example.com/sitemap.xml
```
Is there a reason?

**Comment by regisphilibert** [comment]
We are still in the hugo.Environment using `production` as a default problem... This makes any attempt to use hugo.Environment variable very risky.

**Comment by bubenkoff** [comment]
HUGO_ENVIRONMENT env variable is not respected, only outdated HUGO_ENV is.
