### ISSUE TITLE
Need to extend the footer..

### ISSUE THREAD

**Issue by michaelscloud** [theNewDynamic/gohugo-theme-ananke#232]
Hello, Love the theme it's been easy to set up.

We are using a creative commons picture for the hero image and need to attribute it correctly.

Is there a way to add that detail to the page footer?

Thank you

**Comment by budparr** [comment]
Hi @michaelscloud Have you tried asking in the forums for this? Duplicate the footer into your own layouts/partials directory, and from there do anything you like with it.
