### ISSUE TITLE
Featured image requires absolute path

### ISSUE THREAD

**Issue by metbril** [theNewDynamic/gohugo-theme-ananke#233]
The `featured_image` parameter can be set system wide in `config.toml` or in the front matter of a specific page. This parameter always expects an absolute path from the site root, and does not handle relative urls.

When using it with a page leaf, I have a `posts` section in `content` with folder named `slug-to-page`, containing both an `index.md` and `featured.jpg`:

```
/content/
  posts/
    slug-to-page/
      index.md
      featured.jpg
```

In the index file, I would like to add

```yaml
featured_image: featured.jpg
```

or

```yaml
featured_image: ./featured.jpg
```

The link to the header background image now trims the `'/'` and then makes the path absolute with `absUrl`.

https://github.com/budparr/gohugo-theme-ananke/blob/15a454034900cc0b969db8af490ff77013757624/layouts/partials/page-header.html#L4

Instead, I would like some logic like:

> If it is an absolute path (starting with '/') then leave as is, otherwise precede relative path with permalink from current page.

Something like this:

```go
{{ if not hasPrefix $feature_image "/" }}
  {{ $featured_image := (path.Join( .Permalink $featured_image) }}
{{ end }}
```

**Comment by metbril** [comment]
This snippet seems to work

```go
  {{ $featured_image := string (path.Join .URL $featured_image) }}
```

**Comment by cmlnet** [comment]
Another possibility would be to change the line in page-header.html to use the GetFeatureImage function, which is already used for the summary with images:

`{{ $featured_image := partial "func/GetFeaturedImage.html" . }}`

Or do I miss something here?

**Comment by pmorch** [comment]
This is only part of the problem. Under "Recent Posts", there is a similar line in `layouts/partials/summary-with-image.html`. However, replacing that line with `{{ $featured_image := partial "func/GetFeaturedImage.html" . }}` or `{{ $featured_image := string (path.Join .URL $featured_image) }}` *doesn't* work.

So for the time being, I have a `static/featured_images/` folder where I store the featured images. Which sort of kills the entire idea of page bundles... :-(

**Comment by regisphilibert** [comment]
I'm sorry for the no answer @pmorch , but I refactored the featured image logic taken into account your suggestion! Thanks for that!
