### ISSUE TITLE
Params.description does not display on site header

### ISSUE THREAD

**Issue by corch** [theNewDynamic/gohugo-theme-ananke#238]
On the demo site it appears as though the site description set by params.description in config.toml appears under the site title, however on a fresh install of this theme the description does not display. Is there some other config setting which needs to be turned on to make this work (or how else to get a subtitle to display on the header image?),

**Comment by alienxp03** [comment]
Replacing `.Params.description` with `.Site.Params.description` works.

**Comment by fpiantini** [comment]
I solved copying also the `_index.html` file from `exampleSite/content` of the ananke theme, to my site `content` directory (and obviously customizing it). It seems that something is not working with the `description` parameter in the `config.toml` file, but in any case the `_index.html` overrides it... with some duplication, but also with the added value that you can customize the home page of your site.
