### ISSUE TITLE
Make Multilingual aware

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/gohugo-theme-ananke#257]
The theme should sport a minimum of 2 languages (strings localization) and a lang switch.

We should make sure that adding languages for users is just about configuring Hugo properly through their config file and add their own `/i18n/{XX}.yaml` file if said language is not among the 2 supported one.

There was already an issue for this (#144) but we should start fresh. 

This is more an Epic than an Issue :man_shrugging:

**Comment by budparr** [comment]
As pointed our in #269 we should include translated content in our example set of content shipped with the theme. And, we should include it in the demo.

**Comment by jan-xyz** [comment]
This sounds really awesome! I contributed the current implementation, and would like to know more as to what the plan is, and if I can support again or do something?
