### ISSUE TITLE
How to justify text in posts?

### ISSUE THREAD

**Issue by SDiamante13** [theNewDynamic/gohugo-theme-ananke#263]
My text is not aligned on the right side. I would like to justify it so there are no gaps on the right side. I tried adding customCss like [this issue](https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/20) suggests. Do we have any ability to do this for this theme?

**Comment by prdm0** [comment]
Any solution to this problem? I would also like to justify my text.

**Comment by prdm0** [comment]
Solution. Add in `/static/css/custom.css` the code:

```
.cf {

text-align: justify;

opacity: 1.0;

width: 100%;

height: auto;
}
```
 

.nested-links{

text-align: justify;

opacity: 1.0;

width: 100%;

height: auto;

}

My website: https://prdm0.rbind.io/

**Comment by SDiamante13** [comment]
This can be closed. It is working for me now! Thanks @prdm0!

**Comment by KIRTISNIGDHA** [comment]
> Solution. Add in `/static/css/custom.css` the code:
> 
> ```
> .cf {
> 
> text-align: justify;
> 
> opacity: 1.0;
> 
> width: 100%;
> 
> height: auto;
> }
>  
> .nested-links{
> 
> text-align: justify;
> 
> opacity: 1.0;
> 
> width: 100%;
> 
> height: auto;
> 
> }
> ```
> 
> My website: https://prdm0.rbind.io/

Hi 
I a still struggling to justify the posts. I tried following your suggestion. Can you please provide me more instruction on what should I do after creating the CSS file. Thank you.

**Comment by veenavijai** [comment]
@KIRTISNIGDHA you need to add this line in config.toml under params: 
custom_css = ["css/custom.css"]

**Comment by KIRTISNIGDHA** [comment]
> @KIRTISNIGDHA you need to add this line in config.toml under params:
> custom_css = ["css/custom.css"]

Thank you so much @veenavijai ... It worked !!!
