### ISSUE TITLE
Add twitter hashtag on social share

### ISSUE THREAD

**Issue by chaspy** [theNewDynamic/gohugo-theme-ananke#264]
When clicked social share button, default text includes only title and URL
![](https://user-images.githubusercontent.com/10370988/77242283-39b39a80-6c40-11ea-96af-9d07c240ef1e.png)
.
Can I post a hashtag as a paramater in the post and post it if there is one?

example:

content/post/chapter-1.md

## ```diff
date: 2017-04-09T10:58:08-04:00
description: "The Grand Hall"
featured_image: "/images/Pope-Edouard-de-Beaumont-1844.jpg"
tags: ["scene"]
title: "Chapter I: The Grand Hall"

## +hashtags: ["hugo","ananke"]
Three hundred and forty-eight years, six months, and nineteen days ago
to-day, the Parisians awoke to the sound of all the bells in the triple
circuit of the city, the university, and the town ringing a full peal.

    
    layouts/partials/social-share.html
    
    ```diff
    {{ $title := .Title }}
    {{ $url := printf "%s" .URL | absLangURL }}
    {{ $icon_size := "32px" }}
    +{{ $hashtags := "What Should I do?" }}
    
    {{ if not .Params.disable_share }}
      <div id="sharing" class="mt3">
    
        {{ $facebook_href := printf "https://www.facebook.com/sharer.php?u=%s" $url }}
        <a href="{{ $facebook_href }}" class="facebook no-underline" aria-label="share on Facebook">
          {{ partialCached "svg/facebook.svg" (dict "size" $icon_size) $icon_size }}
        </a>
    
    -   {{ $twitter_href := printf "https://twitter.com/share?url=%s&text=%s" $url $title}}
    +   {{ $twitter_href := printf "https://twitter.com/share?url=%s&text=%s" $url $title $hashtags}}
        {{ with .Site.Social.twitter }}
          {{ $twitter_href = printf "%s&via=%s" $twitter_href . }}
        {{ end }}
        <a href="{{ $twitter_href }}" class="twitter no-underline" aria-label="share on Twitter">
          {{ partialCached "svg/twitter.svg" (dict "size" $icon_size) $icon_size }}
        </a>
    
        {{ $linkedin_href := printf "https://www.linkedin.com/shareArticle?mini=true&url=%s&title=%s" $url $title }}
        <a href="{{ $linkedin_href }}" class="linkedin no-underline" aria-label="share on LinkedIn">
          {{ partialCached "svg/linkedin.svg" (dict "size" $icon_size) $icon_size }}
        </a>
      </div>
    {{ end }}%What do you think?
If accepted, I will be able to create a PR if you are provided with an implementation policy.

Thanks!

**Comment by budparr** [comment]
I like the idea. With a PR, please include documentation for the readme. 

Let's check quickly with @regisphilibert first though. Do you agree, and does that code stand? If empty `$hashtags` need a check?

**Comment by budparr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/6jcJq0Pu/3431-test)

**Comment by regisphilibert** [comment]
Well this is a Twitter only parameter. So I'd rather it's `twitter_hashtag`. In the front matter, unless you can devise a use case where we'd use this elsewhere.

```
{{ $twitter_href := printf "https://twitter.com/share?url=%s&text=%s" $url $title $hashtags}}
```
Not sure how `printf` will handle this third parameter with only two `%s` in the string. We should built a default `$text` string based on the title, and then add the hashtags to it if `.Params.hashtags` is found. Like we're doing with `.Site.Social.Twitter`.

**Comment by chaspy** [comment]
I agree with you, about something like `twitter_share_append` .
What about `additional_comments_for_sharing` (long 😅) as we can be used for sharing to other social media?
