### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by prdm0** [theNewDynamic/gohugo-theme-ananke#294]
Dears,

how to add search functionality? This is something that I think is very important, especially when the site increases in size.

**Comment by budparr** [comment]
Hi @prdm0 That's a pretty complicated endeavor, though I agree it would be a good thing to have. I'll leave this open as a feature request and we'll see if we can come up with a good solution.

**Comment by regisphilibert** [comment]
This is not on the scope of this theme.
