### ISSUE TITLE
Make it a Module

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/gohugo-theme-ananke#307]
init the theme as a Hugo Module (Go Module)

**Comment by budparr** [comment]
Being that modules are superior to Git Submodules and cloning or copying, this could be a nice feature. We should create it in such a way that the module is as easy to implement as possible for (relatively) non-technical users and we document steps as well as pitfalls (things to check if it doesn't work).

**Comment by regisphilibert** [comment]
Hugo Module as a theme work just like other themes except they point to a repo. So I'm confident this will be very easy to use.

```yaml
# config.yaml
theme
- github.com/theNewDynamic/gohugo-theme-ananke
- other_theme
```

When you want to upgrade though, then, just like for a submodule, you need a manual intervention in the command line:
```
hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke
```

**Comment by budparr** [comment]
But are there not implications for where one deploys the theme? Like for Netlify we have to specify a Go version, I think.

**Comment by ariznaf** [comment]
I have tried to follow the instructions to use the theme as a hugo module but it does not work.

I have tried to use
hugo init github.com/theNewDynamic/gohugo-theme-ananke

and  I tried too
hugo init github.com/theNewDynamic/gohugo-theme-ananke

There is no erro message, but when I try to config the theme in my config.toml file  like this:
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

I get this error:

Error: module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "D:\\Users\\fernando\\Documents\\GitHub\\pruebaHugo\\themes".: module does not exist

If I do 
hugo mod verify

I get a similar error.

How do you install or download the module using hugo mod?

In the readme.md there is no instructios about it.

**Comment by regisphilibert** [comment]
Hi @ariznaf. This issue is outstanding as we still have to make sure the Go version set on the module is not going to be problematic. So the doc is wrong as this needs to be imported as a repo rather than used as a theme. 

While this issue remains open you should actually.
1. init you own project as a Hugo Module: `hugo mod init {your repo url}
2. Import the repo through your module config settings:
```yaml
module:
   imports:
   - path: github.com/theNewDynamic/gohugo-theme-ananke
```

**Comment by regisphilibert** [comment]
Hi @ariznaf. It's actually your own repo which needs to be "init" as a Hugo Module.
From the root dir:
`hugo mod init {your project's repo URL}`

**Comment by ariznaf** [comment]
I am not sure to understand the answer.

I have tried to do:

hugo mod init https://github.com/ariznaf/mygithubsiteforHugo

And thet the init for ananke theme too.

But the problems remain.

For now I am using git submodules that work well.

But using hugo modules and being able to upgrade without having to worry about the theme in my git repository seems a good solution.

**Comment by regisphilibert** [comment]
Could you add me to the repo or create a temporary public one for me to take a look?

**Comment by ariznaf** [comment]
Thank you.
I have added you to the Hugo site.

It has nothing special, just Hugo site with ananke theme (and some tries to configure sections in content).

**Comment by regisphilibert** [comment]
See this branch: https://github.com/ariznaf/fuentes-arizna-alzu.org/tree/ananke-as-module

All I did was

1. `hugo mod init github.com/ariznaf/fuentes-arizna-alzu.org/tree/ananke-as-module` which created the `go.mod` file. 
2. And the other changes to the config file which are commited.

**Comment by ariznaf** [comment]
Thank you.
My hugo version is the last, I have installed it a couple of days ago.
Hugo version says 0.79/extended

I am a bit confused with what you tell me to do.

The point of using ananke theme as a go mod in hugo is not having to install it under your themes directory as a submodule, and let you upgrade it easily, isn't it?

The alternate way (previous way of doing things) is using the theme as a git submodule and using git to update it.
If I use hugo mod init as you say, I have to download and install it in my respository.
To upgrade it I would have to upgrade first the code in my repository and then use hugo mod to upgrade the hugo go module.

What is then the point in using hugo modules instead of git submodules?

**Comment by ariznaf** [comment]
OK, I had missed the point.

I thought the hugo mod wast going to be take from my repository under themes/ananke.

But I cannot see any change to the code in the ananke-as-modules branch. It is even with master.

Have you commited the changes to github?

**Comment by regisphilibert** [comment]
I had not sorry about that :(

**Comment by ariznaf** [comment]
Haha... I am quite new to github and git too, so I was getting mad thinking I had not been able to pull changes.

Thank you.

**Comment by ariznaf** [comment]
Well I pulled your branch and did as demanded, but the error continues to be the same.

Here is the output:
![image](https://user-images.githubusercontent.com/57560645/102697241-ad68ef00-4234-11eb-90ff-2d4a6b85436b.png)

And here a cut from the screen showing config section in config.toml


![image](https://user-images.githubusercontent.com/57560645/102697258-d5585280-4234-11eb-92c0-b29bb34c10d6.png)


I am running under windows 10 and a hugo/extended 0.79 version.

May it be a bug? hugo mods not working well under windows?

**Comment by regisphilibert** [comment]
The messages says "You need to install Go" > https://golang.org/doc/install

**Comment by ariznaf** [comment]
OK, thanks. Now it works.

I had installed go, but I think I had forgotten to close and reopen the cmd windows from where I was running the commands, and it did not refresh the environment variables.

Thank you for your help.

**Comment by budparr** [comment]
This looks resolved. I'll close for now.
