### ISSUE TITLE
Embellish post list

### ISSUE THREAD

**Issue by melvinsalas** [theNewDynamic/gohugo-theme-ananke#309]
Is it possible to add this features to the post list?

1) Show Post Image
2) Show date
3) Show less text

Or where can I change it and I'll add it on a Pull Request?

![CleanShot 2020-07-06 at 00 43 07@2x](https://user-images.githubusercontent.com/708747/86563724-20e6a080-bf22-11ea-9773-560edf615d91.png)

**Comment by regisphilibert** [comment]
For 3. User can adjust summary length using the site configuration key `summaryLength`. Default is 70 I think.

**Comment by regisphilibert** [comment]
We'll potentially address this in #466
