### ISSUE TITLE
Styling Help: aligning text in the _index.md

### ISSUE THREAD

**Issue by Unique-Divine** [theNewDynamic/gohugo-theme-ananke#310]
Which files do I need to edit in order to switch the page description to a left-aligned markdown instead of a centered one?

To be more specific, on [this page I'd like to make with the Ananke theme](https://unique-divine.github.io/projects/), having the "Table of Contents " portion of the `_index.md` left-aligned would allow me to make a more aesthetic table of contents. I apologize in advance for being a noob.

**Comment by lyndwyrm666** [comment]
You can find the solution in #158
