### ISSUE TITLE
Ability to create submenus

### ISSUE THREAD

**Issue by Bas-Man** [theNewDynamic/gohugo-theme-ananke#311]
Hi,
I am new to Hugo.
I have been reading on how to create submenus in hugo.
I came across this link in my research https://codingnconcepts.com/hugo/nested-menu-hugo/
Unfortunately I have not been able to get a result.

Does this theme support sub-menus and if not could I request this feature?

Many thanks,

**Comment by budparr** [comment]
Hi @Bas-Man We'll discuss and get back to you. I'm pretty sure it's not possible at the moment.

**Comment by vswitch** [comment]
Any update on this? I'm running into the same issue.

**Comment by matt-sharp** [comment]
I've been trying to follow the same instructions without success.  Is there any update on this feature?

**Comment by matt-sharp** [comment]
Before I dive in and have another go at this, has anyone else managed to get a sub-menu working?

**Comment by DecaTec** [comment]
I also tried to implement sub menus without success.
Any chance that this might work in the future?

**Comment by oza4h07** [comment]
I'll second having this feature would be very helpful.
As a first step, just having two levels menus would enough for many.
