### ISSUE TITLE
Ananke - Blog page and Bullets

### ISSUE THREAD

**Issue by JeromeMain** [theNewDynamic/gohugo-theme-ananke#312]
I purchased Ananke. I imported the demo data. I have 2 issues:

1. The blog page has no navigation. The page came with the demo data. I did not create it. But it has no navigation at the top. See link below.

http://stratafin.co.za/blog/

2. I cant use bullets in my list. Bullets and numbers don't appear.
See link below.
http://stratafin.co.za/process/

**Comment by budparr** [comment]
Hi @JeromeMain Thanks for reporting. We'll take a look at these. Do you have menu items set and they're not showing up? 
It might be helpful if you shared your repo.

**Comment by JeromeMain** [comment]
Hi. The site only has one menu. It shows on every page except the blog page for some reason.

**Comment by JeromeMain** [comment]
I want the menu to show on all the pages

**Comment by budparr** [comment]
The other pages are Ananke as well? We may not be able to help much without seeing your repository.

**Comment by JeromeMain** [comment]
Hi. What is a repository? The entire site is Ananke. So the blog came with Ananke.

**Comment by budparr** [comment]
Hi @JeromeMain I'm wondering if you have the wrong Ananke. This (our theme Ananke) is not a Wordpress theme and we don't sell it. If you purchased a theme I think it best you go to the folks you purchased it from.
