### ISSUE TITLE
Shortcode: youtube not show on page

### ISSUE THREAD

**Issue by Bas-Man** [theNewDynamic/gohugo-theme-ananke#313]
Hi.

I have just tried to add my first youtube link using the shortcode for youtube. Unfortunately it does not appear to work.
I found this reference.

https://rguske.github.io/post/youtube-hugo-shortcode-workaround-when-youtube-wont-work/
and this also https://github.com/eueung/hugo-casper-two/issues/5#

Is the youtube shortcode also broken with this theme?

**Comment by budparr** [comment]
Hi @Bas-Man The youtube shortcode is a Hugo internal template, not a theme thing, but it works as far as I know. I used it just a few days ago. You might have better luck on the Hugo forums. However, If you can post a link to your repo we can have a look for you.

**Comment by Bas-Man** [comment]
Ah. In that case I will test using HUGO_ENV set to production. It appears internal templates don't load if it's not built as production. 
I will test tomorrow morning. 
Thanks for the quick response. 
I will let you know the result tomorrow.

**Comment by budparr** [comment]
FYI: That's not so. The internal templates should load no matter the environment.

**Comment by Bas-Man** [comment]
Regarding templates: There is some code in this theme to prevent things like google analytics, so I probably overly generalized. My mistake.

markdown code
```md
YouTube:
{{< youtube R_-oGJBg3nw >}}

[GitHub](https://github.com/Godsont/Cookie-Consent-Banner)
```

generated html 
```html
You can find the references below:</p>
<p>YouTube:
</p>
<p><a href="https://github.com/Godsont/Cookie-Consent-Banner">GitHub</a></p>
```

I am running the following version:
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown

I could of course just be making a simple mistake.

**Comment by budparr** [comment]
I tried your video and it works for me. I published a page on the demo site with another video: https://gohugo-ananke-theme-demo.netlify.app/post/chapter-1/

**Comment by Bas-Man** [comment]
I have had to use a custom short code. 
I will keep looking into it for a little while.

**Comment by Bas-Man** [comment]
I think I have found my issue. 
Related to privacy settings. 
I will have to test later today to confirm. 
I found it after looking at the actual YouTube template code.

**Comment by Bas-Man** [comment]
Sorry. This was due my over zealous attempt to provide privacy.
in the config.toml I had added.

```txt
  [privacy]
    [privacy.youtube]
      disable = true
```
This can be closed.

**Comment by budparr** [comment]
Glad you figured it out!

**Comment by lkoepsel** [comment]
I understand this is closed, however, it might happen a lot. I too was "over-zealous" in my privacy settings and had YouTube
 disabled. It might be of value to put it in the documentation.
Thank you, Bas-man.
