### ISSUE TITLE
hugo -e production appears not work with this template.

### ISSUE THREAD

**Issue by Bas-Man** [theNewDynamic/gohugo-theme-ananke#315]
Hi,

More a question at this stage. I have been looking into the difference between running:
HUGO_ENV=production hugo
and
hugo -e production

When I run the first option my google async is included in the build, but when I run with "hugo -e production" the async is not added

From the baseof.html line 8:
```html
    {{ hugo.Generator }}
    {{/* NOTE: For Production make sure you add `HUGO_ENV="production"` before your build command */}}
    {{ if eq (getenv "HUGO_ENV") "production" | or (eq .Site.Params.env "production")  }}
```

Running "hugo -e production serve" gives the following output 
```bash
hugo -e production serve

                   | EN  
-------------------+-----
  Pages            | 61  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 17  
  Processed images |  0  
  Aliases          |  6  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 185 ms
Watching for changes in /Users/aspann/Documents/Development/hugo-sites/bas-man.github.io-source/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /Users/aspann/Documents/Development/hugo-sites/bas-man.github.io-source/config.toml
Environment: "production"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```
Note Environment is set to production
I was wondering if an extra condition is need to work with the -e flag for hugo?

Thoughts?

**Comment by Bas-Man** [comment]
Some further investigation indicates that "hugo" run by it self is "production"

I will do some checking, but from this thread: https://discourse.gohugo.io/t/questions-about-hugo-environment-variables/17865/7
I will see if I can check a different envonrment variable during build.

**Comment by Bas-Man** [comment]
Found here:https://discourse.gohugo.io/t/questions-about-hugo-environment-variables/17865

```txt
Since version 0.53 the following code works perfectly:

{{ if eq hugo.Environment "production" }}
<yourhtml />
{{ end }}
```
and 
```txt
{{ if hugo.IsProduction }}
<yourhtml />
{{ end }}
```

I will be changing this code on my site.

**Comment by budparr** [comment]
Hi @Bas-Man Is this safe to close or do you still have questions? If you think your work above might be helpful to others I may label it so people can find it.

**Comment by Bas-Man** [comment]
Yes. Please close. 
Labelling it would be a good idea. 
It effects people who might be using a workflow to publish from a private repo to a public repo.
