### ISSUE TITLE
Background image does not appear on main menu

### ISSUE THREAD

**Issue by mustafasakalli** [theNewDynamic/gohugo-theme-ananke#316]
Hi folks,
I've been trying to do add background image to main menu as I saw theme's default page, but whenever I try it always looks like this.
![Screen Capture_select-area_20200716182124](https://user-images.githubusercontent.com/23080078/87689683-2ef1b800-c791-11ea-9ef1-0013a5f49293.png)

What should I do?

**Comment by budparr** [comment]
Hi @mustafasakalli I think we'd need to see your repo to help you.

**Comment by mustafasakalli** [comment]
@budparr Hello Sir, here is my repo https://github.com/mustafasakalli/mustafa_blog. I must say the the picture I want to put the menu called "background.jpg"

**Comment by budparr** [comment]
Try changing https://github.com/mustafasakalli/mustafa_blog/blob/master/config.toml#L41:
from:
`featured_image = "img/background.jpg"`
to:
`featured_image = "/background.jpg"`

You need to have the forward slash before the file path to make it relative, and you had `img` but the image resides at the root (i.e. in the static folder, not `static/img`)

I'll close the issue, but feel free to open if that doesn't work

**Comment by mustafasakalli** [comment]
Thank you my problem has been solved !
