### ISSUE TITLE
Problems in quickstart instructions

### ISSUE THREAD

**Issue by pvonmoradi** [theNewDynamic/gohugo-theme-ananke#318]
I've created a hugo site. Followed the instructions to add the ananke theme. The instructions are incorrect. For example why in `config.toml` theme name is "gohugo-theme-ananke" where it should be just "ananke"? And the line `themesDir = "../.."` should be deleted but in instructions the wording was put in a way that it seems it is not necessary.

**Comment by budparr** [comment]
The quickstart instructions appear correct to me. Are you speaking of these: https://gohugo.io/getting-started/quick-start/ ?

**Comment by pvonmoradi** [comment]
@budparr no, I meant [https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/README.md#the-config-file](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/README.md#the-config-file)

**Comment by budparr** [comment]
I use "gohugo-theme-ananke" in the demo. Just make it whatever you name the folder.

**Comment by pvonmoradi** [comment]
Then shouldn't the instructions [here](https://github.com/theNewDynamic/gohugo-theme-ananke#installation) be updated to :  
```
$ git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/gohugo-theme-ananke
```

**Comment by budparr** [comment]
The demo is really just a demo, not part of the instructions, and shows that there are several ways to do it. But I see your point, and I'll consider changing it.
