### ISSUE TITLE
Background image and some posts won't get loaded in remote view

### ISSUE THREAD

**Issue by pvonmoradi** [theNewDynamic/gohugo-theme-ananke#319]
I'm reproducing the exampleSite of the theme. I can see the background image on header and all posts in my localhost. But in my phone, neither FF nor Chrome show that image. Also _some_ posts can't be seen on the phone. I guess this is also because of their featured image. Where is the problem?

I'm using the following command : `hugo server  --bind=0.0.0.0`
[The rendered website on localhost (PC)](http://i.imgur.com/S1X5wCk.png)
[The rendered website on an android phone on the local network](https://imgur.com/a/fCW7xVi)

**Comment by budparr** [comment]
You'd need to share your repo for us to help you.

**Comment by pvonmoradi** [comment]
It was creating by:  
1- `hugo new site mysite`  
2- initializing git
3- adding ananke theme 
4- copy pasting /themes/ananke/exampleSite/ to the root dir (so contents are created)
5- fixing the config.toml
It is a reproduced build of the instructions and exampleSite

**Comment by budparr** [comment]
The demo (linked to in the readme) works. If you don't have a repo to share, perhaps make sure your setup matches that.
