### ISSUE TITLE
My google analytics is not working

### ISSUE THREAD

**Issue by SarthakNarayan** [theNewDynamic/gohugo-theme-ananke#321]
I have the google tracking ID in config.toml file. Also, I run it as HUGO_ENV=production hugo server -D still active users are shown as 0. I am using github to host my website.  Please help I don't know why it is not working

**Comment by budparr** [comment]
Hi @SarthakNarayan Can you share your repo, please? Also might be worth a check on the Hugo forums, because this sounds like a problem other may have had and solved.

**Comment by SarthakNarayan** [comment]
https://github.com/SarthakNarayan/Website
This is my repo containing the Hugo files

**Comment by budparr** [comment]
@SarthakNarayan Looks like you've commented out the theme's Google analytics and are using your own hard-coded Google analytics. The latter seems to be rendering. I can't really help you troubleshoot your own GA implementation, only things that have to do with the theme.

**Comment by SarthakNarayan** [comment]
I have tried the one that comes with the theme but it didn't seem to work for me. You can try it out. This forced me use other methods as mentioned in forums.

**Comment by budparr** [comment]
I uncommented the theme's Google analytics and it works fine for me.

![Screen Shot 2020-07-30 at 9 35 12 AM](https://user-images.githubusercontent.com/115347/88929334-fe595600-d247-11ea-9188-f991e615608c.jpg)

**Comment by budparr** [comment]
that's running the command you posted: `HUGO_ENV=production hugo server -D`

**Comment by SarthakNarayan** [comment]
So I should either uncomment script given by Hugo or replace my code by above
![image](https://user-images.githubusercontent.com/42849256/88929779-37211b80-d298-11ea-9fb0-eb7d381f23c3.png)

**Comment by budparr** [comment]
I can't comment on the Google Tag manager code. I can say that this:

```
{{ if eq (getenv "HUGO_ENV") "production" | or (eq .Site.Params.env "production")  }} 
      {{ template "_internal/google_analytics_async.html" . }}
    {{ end }}
```
appears to work as intended.

**Comment by SarthakNarayan** [comment]
I did whatever you told me to do
![image](https://user-images.githubusercontent.com/42849256/88930769-8a479e00-d299-11ea-8d76-1b6a44dcad17.png)
My site is also open on local host. Still no active users
![image](https://user-images.githubusercontent.com/42849256/88930797-97fd2380-d299-11ea-8da8-42f0a3921823.png)

**Comment by budparr** [comment]
You're only running it on localhost? Why don't you try putting it up on a server. GA may take some time to register. They have a place in the admin panel to let you know if the code is being picked up, which is a better way than trying to see active users from localhost.

**Comment by SarthakNarayan** [comment]
Forums said it should also work on localhost and I tried deploying it on github and then testing it but still no views were registered. The spike in the above image is at the time when you were running my site using my track id I guess. But I will try what you said.

**Comment by SarthakNarayan** [comment]
Sorry for the trouble. I got it figured. I was using brave browser and it was disabling js. On switching to chrome and firefox it worked perfectly fine.
