### ISSUE TITLE
featured_image is not showing in Netlify

### ISSUE THREAD

**Issue by mkz71** [theNewDynamic/gohugo-theme-ananke#323]
I have featured_image in markdown files.
When I build this in local machine, the image is shown up fine.
But when I deploy it to Netlify, there is no image shown up.
Not sure I have any wrong setup.

**Comment by budparr** [comment]
Hi @mkz71 Can you share your repo, please?

**Comment by mkz71** [comment]
@budparr please check it here, https://github.com/mkz71/quickstart

**Comment by budparr** [comment]
Oh, sorry. Can you also point me to the URL on Netlify?

**Comment by mkz71** [comment]
https://jtk.netlify.app

**Comment by budparr** [comment]
Ah, I see now. You have example.org in your config file:
`baseURL = "http://example.org/"`
You should change that to your actual URL

**Comment by mkz71** [comment]
Wow, it is working now.
I didn't know that we need to update the baseURL too.
Thank you!
