### ISSUE TITLE
site_logo not working on other pages

### ISSUE THREAD

**Issue by mkz71** [theNewDynamic/gohugo-theme-ananke#324]
I add site_logo to config.toml but it is only working on homepage, not other pages.

Please check this links..
https://github.com/mkz71/quickstart
https://jtk.netlify.app/

**Comment by budparr** [comment]
Change 

`site_logo = "img/tiktok-logo.svg"` 

to 

site_logo = "/img/tiktok-logo.svg"

Note, I've added a slash to the image path.
