### ISSUE TITLE
Can we set body color on each page?

### ISSUE THREAD

**Issue by mkz71** [theNewDynamic/gohugo-theme-ananke#325]
Is it possible to set body color for each page instead of setting only one color for the whole site 
in config.toml under body_classes parameter?

Please check this links..
https://github.com/mkz71/quickstart
https://jtk.netlify.app/

**Comment by budparr** [comment]
I believe you should be able to add a `body_classes` param to any page.

**Comment by mkz71** [comment]
You are right.
I add body_classes to front matter and it is working. Thank you!
