### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by mkz71** [theNewDynamic/gohugo-theme-ananke#326]
Where should I add this line of code to Ananke theme?

`{{ template "_internal/google_analytics.html" . }}`

**Comment by budparr** [comment]
It's already there (though we use the async version) https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html#L43

**Comment by budparr** [comment]
Just note to use it: https://github.com/theNewDynamic/gohugo-theme-ananke#production

**Comment by mkz71** [comment]
Oh, I see so I just need to add my GA id in the config.toml file and set the site to production, correct?

**Comment by budparr** [comment]
Yep

**Comment by mkz71** [comment]
When I test this at my local server, it is not working but it is working fine on Netlify.
Is this normal?

**Comment by budparr** [comment]
yes. You don't want to be collecting stats on your local server

**Comment by mkz71** [comment]
I see. Thank you!
