### ISSUE TITLE
How Tag and Related Pages work?

### ISSUE THREAD

**Issue by mkz71** [theNewDynamic/gohugo-theme-ananke#328]
I look at these two pages and they are both tagged with "scene" tag but how come only the first link shows  related page on the right?

https://themes.gohugo.io//theme/gohugo-theme-ananke/post/chapter-4/
https://themes.gohugo.io//theme/gohugo-theme-ananke/post/chapter-1/

**Comment by budparr** [comment]
Hey, @mkz71 those links aren't working for me

**Comment by mkz71** [comment]
@budparr Please check if they are working now.

**Comment by budparr** [comment]
could be because we don't have Related content configured on the example site https://gohugo.io/content-management/related/#configure-related-content

we'll have a look at it soon. Thanks!

**Comment by mkz71** [comment]
I have the same issue on my site.
Please see the links below..

https://jtk.netlify.app/posts/tomkha/
https://jtk.netlify.app/posts/tomyum/

**Comment by Pathsis** [comment]
There is a problem here, in the mobile view, the table of contents is displayed at the bottom of the body along with the related content.

**Comment by jmooring** [comment]
This can be closed. Related content works great.
