### ISSUE TITLE
wrong path of site logo cause 404 error in post pages

### ISSUE THREAD

**Issue by junjieyuan** [theNewDynamic/gohugo-theme-ananke#332]
Because of current site logo' path is ```./path/to/logo```, site logo can **only** loaded in **homepage**.

https://github.com/theNewDynamic/gohugo-theme-ananke/blob/03fd7d9da05db0928284b601d987c97556c6eb24/layouts/partials/site-navigation.html#L5

**Comment by omontigny** [comment]
> If anyone else experiences this and is still waiting on the fix, I found preceding the path for the logo with `/` (which is different to what you do for `featured_image`) seems to fix/workaround this:
> 
> ```yaml
> favicon: "/images/logo.png"
> site_logo: "/images/logo.png"
> featured_image: "images/header.jpg"
> ```
> 
> Note: These two image files are in `<site dir>/static/images/`

Hello
I have the same problem when the BaseURL is not `http://localhost:1313` but something like this 
`baseURL = "http://localhost:1313/mysite"` 
and the `/` doesn't fix the problem.

if I use : ` site_logo = "images/logo.svg" ` I have logo only on the first main page 
If I use : ` site_logo = "../images/logo.svg"` I have logo on all the other pages except first page

Thanks

**Comment by ben-moss** [comment]
> Hello I have the same problem when the BaseURL is not `http://localhost:1313` but something like this `baseURL = "http://localhost:1313/mysite"` and the `/` doesn't fix the problem.
> 
> if I use : `site_logo = "images/logo.svg"` I have logo only on the first main page If I use : ` site_logo = "../images/logo.svg"` I have logo on all the other pages except first page
> 
> Thanks

Did you try?:
```yml
site_logo = "/images/logo.svg"
```

I have partials for both `page-header.html` and `site-header.html` that contain:
```html
  {{/* Trimming the slash and adding absURL make sure the image works no matter where our site lives */}}
  {{ $featured_image := (trim $featured_image "/") | absURL }}
  <header class="cover bg-top" style="background-image: url('{{ $featured_image }}');">
```

See https://gitlab.com/ben-moss/ben-moss.gitlab.io/-/tree/main/layouts/partials

**Comment by omontigny** [comment]
> Did you try?:
> 
> ```yaml
> site_logo = "/images/logo.svg"
> ```

Yes I did it's really a problem of URL Path. 
if my `BaseURL = http://localhost:1314/mysite` , and` site_logo = "/images/logo.svg"` so the logo is not found because the URL of the logo is : `http://localhost:1314/images/logo.svg` it's like the BaseURL is not used to define URL   of the image. 
Ok I found the solution : I have to define the site_logo like this : `site_logo = "/mysite/images/logo.svg"`
