### ISSUE TITLE
Description is not being displayed in the web page

### ISSUE THREAD

**Issue by CSALS** [theNewDynamic/gohugo-theme-ananke#334]
I followed the exact steps to install this theme but can't seem to figure out why the description is not being displayed in the web page.
Here is the config.toml in the root folder
```
title = "Notre-Dame de Paris"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
```

And here is the result when I do ```hugo serve```
![hugo-issue](https://user-images.githubusercontent.com/31367352/91485088-e0732580-e8c7-11ea-895f-504cd3b9a4c0.JPG)
There's no description

**Comment by budparr** [comment]
Hi @CSALS Can you give us a link to your repo?

**Comment by CSALS** [comment]
@budparr here you go https://github.com/CSALS/testblog
It's just the standard boilerplate created using Hugo. I only added the theme

**Comment by budparr** [comment]
Thanks. It doesn't look like you have any content in your site. Try adding some content and putting the description there. The description in the config is for SEO meta tags as a default.

**Comment by CSALS** [comment]
@budparr The demo shows the description in the web page itself. Where should I add the description to display it on the web page?
![image](https://user-images.githubusercontent.com/31367352/91583092-53cf7280-e96e-11ea-9768-9d16d425e143.png)
Here is the demo image. The description is "The last theme you will ever need"

**Comment by budparr** [comment]
Have a look at the examplesite folder. The description there is in the `_index.md` file, which is the home page.

**Comment by CSALS** [comment]
Oh, thanks. I think you should regarding this in the documentation. AFAIK there is no mention of this file.

**Comment by budparr** [comment]
Glad it worked for you. We'll have a look at the docs!
