### ISSUE TITLE
Tab Order

### ISSUE THREAD

**Issue by mparmis** [theNewDynamic/gohugo-theme-ananke#335]
The tabs are ordered alphabetically, but I want to customize the order. Can you tell me how I can do that?

**Comment by budparr** [comment]
Hi @mparmis Following up here rather than email so others can benefit from the conversation. 

I suggested
> Try adding "weight" to your pages, like this; https://gohugo.io/content-management/menus/#advanced

and that seemed to work for you:
> this helped with all the tabs except the contact tab. I have my tabs weighted as 1,2,3,4 (1 goes first). I want my contact tab to go last so I gave it a weight of 4, but it’s still the third tab. 

The lowest number is `0` so adjusting for that, see if that helps. Otherwise, paste a link to your repo and we'll have a look.

**Comment by mparmis** [comment]
Hi Bud,
The issue is was solved by putting 0 for the last page. Thank you.
