### ISSUE TITLE
Improve documentation on: Link icons in article pages

### ISSUE THREAD

**Issue by mparmis** [theNewDynamic/gohugo-theme-ananke#336]
For the Articles page, each article has a twitter, facebook, and linkedin link. I can't find where in the code I can change or delete those link icons.

**Comment by budparr** [comment]
Hi @mparmis We should make this more clear in the documentation. You can add or remove those by putting in their respective links in the config file. Here's the example: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/exampleSite/config.toml#L18

**Comment by mparmis** [comment]
Hi @budparr changing the links in the config file only changes the link icons at the top right of each page. However, there are also link icons in each article (right above the articles title), and I can't find where I should change those.

**Comment by budparr** [comment]
Can you show me an example?

**Comment by mparmis** [comment]
This is from the example site
![hugo](https://user-images.githubusercontent.com/35639740/91878088-adb48e80-ec33-11ea-8a33-8738c0a61ef3.JPG)

**Comment by budparr** [comment]
Oh, those are the sharing icons. 
If you want to disable them, there's a parameter `disable_share`

Or, the template to change them is here: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/social-share.html

**Comment by mparmis** [comment]
It worked. Thank you.
