### ISSUE TITLE
How to display post summary for Chinese articles?

### ISSUE THREAD

**Issue by qidai628** [theNewDynamic/gohugo-theme-ananke#337]
I am writing posts in Chinese. I find on post list, the whole article, instead of the summary, will display with a more button. It makes the post summary too long. How can I display a proper post summary for Chinese articles?

**Comment by regisphilibert** [comment]
Hi there.

Not sure to understand, is it the whole post? Or the post with a more button?

**Comment by regisphilibert** [comment]
Do you have `hasCJKLanguage` set to true in your config? From [doc](https://gohugo.io/getting-started/configuration/):

> hasCJKLanguage (false)
If true, auto-detect Chinese/Japanese/Korean Languages in the content. This will make .Summary and .WordCount behave correctly for CJK languages.

**Comment by ppcola** [comment]
@regisphilibert Thanks，This solved my problem.
