### ISSUE TITLE
Make part of texts bold

### ISSUE THREAD

**Issue by mparmis** [theNewDynamic/gohugo-theme-ananke#339]
Is it possible to make part of the texts in article descriptions bold?

**Comment by budparr** [comment]
Hi @mparmis I think this is the template you'd need to copy (into your own `layouts/partials` folder) https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/page-header.html#L12

And add the class `b` to the others there. http://tachyons.io/docs/typography/font-weight/

That should work!
