### ISSUE TITLE
How to change max width of text area?

### ISSUE THREAD

**Issue by RoninTech** [theNewDynamic/gohugo-theme-ananke#341]
As you can see here:

[https://themes.gohugo.io//theme/gohugo-theme-ananke/](https://themes.gohugo.io//theme/gohugo-theme-ananke/)

The section that reads: "Welcome to my blog with some of my work in progress...." is very narrow on a big screen.  What do I need to change so that the text uses up a bigger portion of the screen width?

Thanks!

**Comment by budparr** [comment]
Hi @RoninTech You can copy this template into your `layouts` folder: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/index.html#L2 and adjust the classes in line 2. You'll find reference for classes here: https://tachyons.io

**Comment by budparr** [comment]
I should note that it is `measure-wide` that constrains the width of that copy.

**Comment by RoninTech** [comment]
Thanks Bud, it's much appreciated!  Changing measure-wide in my themes layouts/index.html:line2 to mw8 or mw9 gets it closer to what I want.  I'm surprised we can't get a better resolution on possible width changes than just mw1 through mw9, of which mw1 to mw6 are smaller than the original setting.  Something on the order of pixel/em/% resoluion changes would be nice.  Is this a limitation of Tachyons?

**Comment by budparr** [comment]
I see it as a constraint, not necessarily a limitation, but yes, mw9 is the largest. http://tachyons.io/docs/layout/max-widths/
