### ISSUE TITLE
What determines items showing up in main page "Recent Articles"?

### ISSUE THREAD

**Issue by RoninTech** [theNewDynamic/gohugo-theme-ananke#344]
I'm migrating my [ronin-tech.com](https://www.ronin-tech.com) from Google sites to hugo.  I have 3 "categories" of posts: 
"Van Life", "Travels", "Articles" and "Packs".  My Google Sites "Articles" category was randomly named but it appears to have special meaning in Hugo.  All these pages are "articles" in my mind and I would like them to show up in the "Recent Articles" list on the main page.  For some reason only the pages under content/articles/ show up in this list.  How would I go about modifying things so that any pages (other than the _index.md files) can show up under "Recent Articles"?  My folder structure is:

content/

- _index.md
- about.md
- contact.md

content/travels/

- _index.md
- travel_article_one.md
- travel_article_two.md
- ... etc.

content/van-life/

- _index.md
- van_article_one.md
- van_article_two.md
- ...etc.

content/articles/    **!!!  only these items show up under "Recent Articles" on main page.**

- article_one.md
- article_two.md
- ...etc. 

content/packs/

- _index.md
- pack_article_one.md
- pack_article_two.md

I'm really enjoying Hugo and this theme.  After this articles thing, my final TODO is to recreate a dynamic menu similar the one on my Google Sites version.  Basically when you mouseover a menu item that is a parent of other menu items, a dropdown list of the children will be dynamically displayed.  Is anyone aware of a modified ananke theme that has something like this implemented to point me in the right direction?

Thanks

**Comment by RoninTech** [comment]
Awesome!  Ok, found out I wasn't looking at closed posts. and found a reference to adding mainSections to params in config.  So I've added:

mainSections = ["travels", "van-life", "articles", "packs"]

To my config.toml and now I see posts from the 4 categories all under the title "Recent Our Travels" which is the name of the first category.  Should I just hard code the title to be something that encompasses all categories like "Recent Posts" o ris there a better way to show a correct heading?

Thanks again.

**Comment by budparr** [comment]
Glad you found it. Closing for now. Thanks1
