### ISSUE TITLE
Pass variables to head-additions.html

### ISSUE THREAD

**Issue by panssystem** [theNewDynamic/gohugo-theme-ananke#346]
I'm trying to use Azure Application Insights in my site, and to do that well, I'd like to be able to use conditions in the head-additions.html.

I know all it takes is to add the . in the Partials call, but I'm trying to use as a module, so it would be a nice-to-have for me.

**Comment by budparr** [comment]
A few ways to do this, but the partial is wrapped in block tags so can easily be overwritten in templates:
`{{ block "head" . }}{{ partial "head-additions.html" }}{{ end }}`

`{{ block "head" . }}{{ partial "ANYTHINGl" }}{{ end }}`

**Comment by panssystem** [comment]
Thanks @budparr , I'll try to spend some time on it and see what I can do. 

I know when I did a first-pass, head was defined elsewhere so it gave an error, but I'm sure I can work around that somehow. 

What's the reason for not passing variable to head-additions partial though? Is there some deep reason I'm not aware of?

**Comment by budparr** [comment]
@panssystem It's in there now: https://github.com/theNewDynamic/gohugo-theme-ananke/pull/348/files#diff-0c8f747dec0e7ca5148ebe8907cfc781R46

I'll close for now. Re-open if you need anything else. Thanks!
