### ISSUE TITLE
Bing Webmasters tools complains: "Meta Description tag missing"

### ISSUE THREAD

**Issue by DazWilkin** [theNewDynamic/gohugo-theme-ananke#351]
IIUC, this is correct in that there is no `<meta name="description" content=...>` tag added by the theme.

There are however (in my case), 2 other meta descriptions:

```HTML
<meta itemprop="description" content=...>
<meta name="twitter:description" content=... >
```

In an attempt to avoid the Bing error, I added the following to `baseof.html`:

```HTML
<meta name=description content="{{ .Description }}">
```

Q1: Is this the best place to add this?

I had tried it in `head-additions.html` but that page appears to not process template content correctly; I was unable to resolve any combination of `content="{{ .Description }}"` using it nor seemingly any other variable.

Q2: Should `<meta name="description" content=... >` be part of the default theme?

**Comment by budparr** [comment]
As I mentioned in your last issue. https://github.com/theNewDynamic/gohugo-theme-ananke/releases/tag/v2.6.6

**Comment by DazWilkin** [comment]
Apologies for the dupe. Thank you!
