### ISSUE TITLE
Paginated Archive for mainSections users

### ISSUE THREAD

**Issue by stenius** [theNewDynamic/gohugo-theme-ananke#352]
Hey @budparr, I'm building a site with several different content sections and on the main page, I want to have a link that takes me to an archive of all different sections.

Right now, if I have `.Site.Params.mainSections` set, the link only takes me to the first section.

I would like to change it so that link takes me to a paginated page with a complete archive from all sections.

Would you accept a PR for this change?

**Comment by budparr** [comment]
That sounds pretty specific to your use-case, @stenius I think it would be better if you just used your local template override for this. @regisphilibert Any thoughts?

**Comment by stenius** [comment]
Yeah, that's what I ended up doing, but I figured if other people were
displaying multiple sections, they'd assume the "more" button would include
the same content, and not different content, paginated.

I'd need help with a pr review if this is something you want.

**Comment by stenius** [comment]
I'm going to close this out and retract my offer.  Just wanted to say thanks again for the work on the theme (@budparr, @regisphilibert) before I do.
