### ISSUE TITLE
The example site includes "featured_image" as a parameter in the root config.toml 

### ISSUE THREAD

**Issue by cbp123** [theNewDynamic/gohugo-theme-ananke#36]
I don't think the featured image is ever taken from the root config.toml file though - it is only acquired from the front matter on content files. This is a little confusing for first-time users.

**Comment by budparr** [comment]
Thanks, @cbp123 You're right. I've been a bit wishy-washy on how to handle the featured image and need to solidify its use and the explainer comments around it. I'll leave this open until I do.

**Comment by mt-inside** [comment]
Hey, I found this issue when trying to have no featured_image on the site home page. As of today (ananke d5b87cb), the front page (layouts/partials/site-header.html) *does* take its image from params.featured_image in the root config.toml. Note that if you want to turn that image off, "false" is the only zero-value I found - "", nil, 0, etc all give the default image. hth
