### ISSUE TITLE
Large blank behind some short articles in the display box

### ISSUE THREAD

**Issue by Hometown2020** [theNewDynamic/gohugo-theme-ananke#360]
When the length of the article is relatively long, the article page is very long, which will lead to a large blank behind some short articles, affecting the reading experience. I want to know how to modify the CSS file so that the height of the display box can be controlled within the appropriate range?

**Comment by budparr** [comment]
Hi @Hometown2020 Can you show me a screenshot of what you mean? I'm not sure I understand.

**Comment by Hometown2020** [comment]
![blank](https://user-images.githubusercontent.com/60468640/96874255-81392800-14a8-11eb-889c-6134bb940b8d.jpg)

Hi, the problem is just like this. You can see that there are a lot of blanks left behind the two articles on the left.

**Comment by budparr** [comment]
Those blocks are meant to expand to the content. If you manually shorten them, you'll cut off the content. I think you'd be better off using a description field to control what is displayed there. Check out this page: https://gohugo.io/content-management/summaries/#readout

**Comment by Hometown2020** [comment]
OK. I have solved the problem. Thank you for your help!

**Comment by budparr** [comment]
Great!
