### ISSUE TITLE
refer to pdf or word doc

### ISSUE THREAD

**Issue by mikenguyen13** [theNewDynamic/gohugo-theme-ananke#365]
Hello, 
I don't know if this is more like an issue or question. But I was wondering if there is a way I can refer to a document in either pdf or word. For example, I would like to include the word "CV in **PDF** and **Word**" and then link them to the documents. So where should I store the documents and how to should code it?

**Comment by budparr** [comment]
I think this is more of a question for the Hugo forums: https://discourse.gohugo.io
