### ISSUE TITLE
Automatic Plural on Navigation Links

### ISSUE THREAD

**Issue by mymojoh22** [theNewDynamic/gohugo-theme-ananke#369]
Thank you for creating and making available such an awesome theme! I'm having some issues with the navigation link, though, that I can't figure out if it's from the ananke code or my own computer... Every time I go on terminal and add a new site page, it shows up with an "s" at the end of it on the navigation links (top right corner). For ex., I'd put `hugo new dir1/a.md` in terminal, which creates a "dir1" file under Contents, with a.md file in it, but "dir1" shows up as "dir1s" in the navigation links... Is this an issue on my end?

**Comment by budparr** [comment]
I'm not sure. Can you share your repo?

**Comment by jmooring** [comment]
This can be closed. See <https://gohugo.io/getting-started/configuration/#pluralizelisttitles>.
