### ISSUE TITLE
Google New Analytics Tag support

### ISSUE THREAD

**Issue by Bas-Man** [theNewDynamic/gohugo-theme-ananke#372]
Google has launched a new gtag.js Global tagging system.

Will this be added as a new option for Google analytics?

**Comment by budparr** [comment]
Hi @Bas-Man. We use the Hugo tag, so that would be answered there.

**Comment by DazWilkin** [comment]
For anyone else that finds this issue and remains unsure of the fix, see:

Hugo's documentation for [Google Analytics](https://gohugo.io/templates/internal/#google-analytics) and the "including both synchronous and asynchronous tracking codes. As well as support for both v3 (`analytics.js`) and v4 (`gtag.js`) of Google Analytics.".

> **NOTE** Changes are required both in `config.toml` and `./themes/ananke/layouts/_default/baseof.html`.
