### ISSUE TITLE
Pleas add a dark theme option

### ISSUE THREAD

**Issue by ariznaf** [theNewDynamic/gohugo-theme-ananke#373]
I suppose that would be an easy task if you know how the CSS classes are organized.

But I have tried to change the background to a bg-near-black color and it is not so easy.

The background changes but the letter colors are quite dark to be read in many places.

I have tried to change the forground colors like this:

[params]
  background_color_class = "bg-black"
  body_classes = "bg-near-black"
  post_content_classes = "moon-gray"

It works for post pages but there are many other places where letters remain to black.

So having an option to select different skins or color combinations (a dark theme in particular) would be great.

If that is too complicated to be implemented, meanwhile it would be great if you add in the readme a [params] section to get it to work changing the appropiate css classes.

**Comment by 1000283** [comment]
It would be great. I don't use images and the white is glaring for me.

**Comment by budparr** [comment]
Closing for #258
