### ISSUE TITLE
Consider using Hugo Pipes for the CSS and adding functionality for custom CSS overrides

### ISSUE THREAD

**Issue by onedrawingperday** [theNewDynamic/gohugo-theme-ananke#379]
Hello,

Since this theme is used for the Hugo Quick Start Guide please do consider updating the theme to use current Hugo features like Hugo Pipes for the CSS and not the output of a Webpack workflow. ref: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html#L18-L21

Also please consider adding the ability for newbies to easily add Custom CSS .

Currently it is very difficult for new users to override the theme CSS with the present setup, as shown in this [forum topic](https://discourse.gohugo.io/t/complete-beginner-in-website-and-cannot-follow-mathjax-tutorial/30218/6).

**Comment by budparr** [comment]
Thank you, @onedrawingperday We'll be making some improvements in January.

**Comment by regisphilibert** [comment]
@budparr I want remove webpack altogether. Currently the script is an empty shell that can be overwritten by users. We'll leave it as an empty shell, and users will only have to overwrite it inside `assets/ananke/js/main.js` in order for it to be processed by `js.Build`. 

Won't it be a problem for users relying on webpack? I think those are fairly advanced since they must compile the theme's assets already but who knows...

**Comment by z3ntu** [comment]
FYI #387 completely removes the CSS on my site, without changing my site config. As the commit message says "optional", I think that's a new bug?
If you need more info I can provide them.

**Comment by regisphilibert** [comment]
@z3ntu can you share your repo?

Thanks!

**Comment by budparr** [comment]
@z3ntu when you share your repo can you please just start a new issue?

**Comment by z3ntu** [comment]
False alarm it seems. It's just a problem when `hugo server` is running and you switch from the theme before this commit to this commit. Apparently hugo gets confused and doesn't serve css anymore. Restarting `hugo server` fixes it.

Log from checking out a newer version of ananke - for reference:
```
Change of Static files detected, rebuilding site.
2021-03-16 14:15:48.268 +0100
File no longer exists in static dir, removing /dist/css/app.1cb140d8ba31d5b2f1114537dd04802a.css
File no longer exists in static dir, removing /dist/css/app.4fc0b62e4b82c997bb0041217cd6b979.css
File no longer exists in static dir, removing /dist/css/app.7e7787cc1402d7de28bc90f7e65adf96.css
File no longer exists in static dir, removing /dist/css/app.e6e75cdafe2e909dacfabeb26857f994.css
File no longer exists in static dir, removing /dist/js/app.3fc0f988d21662902933.js
File no longer exists in static dir, removing /dist/css
File no longer exists in static dir, removing /dist/js
File no longer exists in static dir, removing /dist

Change detected, rebuilding site.
2021-03-16 14:15:48.269 +0100
Data changed "/my/site/themes/ananke/data/webpack_assets.json": REMOVE
Template changed "/my/site/themes/ananke/layouts/partials/site-scripts.html": REMOVE
i18n changed "/my/site/themes/ananke/i18n/hu.toml": WRITE
i18n changed "/my/site/themes/ananke/i18n/tr.toml": WRITE
i18n changed "/my/site/themes/ananke/i18n/zh-tw.toml": WRITE
Template changed "/my/site/themes/ananke/layouts/_default/baseof.html": WRITE
Template changed "/my/site/themes/ananke/layouts/index.html": WRITE
Template added "/my/site/themes/ananke/layouts/partials/site-style.html": WRITE
Template added "/my/site/themes/ananke/layouts/robots.txt": WRITE
Total in 44 ms
```
