### ISSUE TITLE
LaTeX support?

### ISSUE THREAD

**Issue by wrshoemaker** [theNewDynamic/gohugo-theme-ananke#38]
Love the style. Just made my personal website with it. Are there any plans to support LaTeX in the future? Or is that feature already supported?

**Comment by budparr** [comment]
Thank you, @wrshoemaker  - I don't know how to do that. Maybe @rdwatters knows?

**Comment by rdwatters** [comment]
I have very little knowledge of LaTeX. Sorry @wrshoemaker, @budparr I've used a hack with Pandoc, Word default styles, and some ugly AppleScript when I needed to generate both HTML pages and PDF from a single markdown file.

I'm sure a LaTeX guru could make quick work of this with custom outputs, but in 2017, I feel like it's a better use of time to focus on a solid print stylesheet in the event users want to `Ctrl+P>Save to PDF`...and most of my use cases don't care printing and print formats, TBH...

**Comment by piever** [comment]
Not sure if this can be streamlined, but the following worked for me.

1) Add this code snippet in the "partials":

```
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          <!-- inlineMath: [['$','$'], ['\\(','\\)']], -->
          <!-- displayMath: [['$$','$$'], ['\\[','\\]']], -->
          processEscapes: true,
          processEnvironments: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
          TeX: { equationNumbers: { autoNumber: "AMS" },
          extensions: ["AMSmath.js", "AMSsymbols.js"] }
          },
        CommonHTML: { linebreaks: { automatic: true } },
        "HTML-CSS": { linebreaks: { automatic: true } },
        SVG: { linebreaks: { automatic: true } }
      });
    </script>
    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
```

2) Add `markup: mmark` at the beginning of the post:

```
date: 2017-11-15T00:17:23Z
markup: mmark
draft: false
```

3) Enclose equations in dollars:

`$$\varphi = \frac{1}{\varphi-1}$$`

Example is from [here](https://piever.github.io/simpleblog/posts/julia_chapter2/), code [here](https://github.com/piever/simpleblog/blob/master/layouts/partials/site-footer.html#L3).

The only part where the theme could help is in including the code snippet above by default I guess.
