### ISSUE TITLE
Does Ananke support multilingul function?

### ISSUE THREAD

**Issue by hellojinwoo** [theNewDynamic/gohugo-theme-ananke#380]
First of all, I would really appreciate for making Ananke, such a beautiful Hugo theme. I, however, have a question regarding Ananke's support for multi-langues.

__Question__
- Can multilingual mode, which has been discussed in several other issues, be supported in Ananke?
- If the multilingual support is not implemented yet, can you kindly give a walk through of how to set it up on Ananke?

__More in detail__
- Ananke is introduced as a multilingual theme in gohugo web page. (https://themes.gohugo.io/tags/multilingual/)
- I know that `multilingual` is a topic that has been already discussed in #108 #144 
- It seems like through pull requests of contributors, these multilanguage function is now reflected in the theme.
- However, in the exampleSite folder or in demo webpage, I cannot find the multilingual support.

**Comment by budparr** [comment]
HI @hellojinwoo Yes, you can use the theme with multiple languages. You're right though, we need to set up the example better. I'll add that to our list to handle for the new year.

**Comment by hellojinwoo** [comment]
Thank you for your reply @budparr . Can you show me examples to add another language to the English-based Ananke github pages?
