### ISSUE TITLE
Posts use only about 30% of screen width

### ISSUE THREAD

**Issue by tuck1s** [theNewDynamic/gohugo-theme-ananke#381]
![Screenshot 2020-12-29 at 23 45 09](https://user-images.githubusercontent.com/11942927/103321151-2683f580-4a30-11eb-9c8c-9ecba81eefb0.png)

by default, posts seem to use only a middle portion of the screen on a standard 1920x1080 monitor. Checked this on both Chrome and Firefox on a Mac.

is there a way to get the article to fill out the width a bit more? Ideally with a global setting, I don't need this to be different on every article.

**Comment by budparr** [comment]
That's by design. We use a readable line length. Here's one source https://practicaltypography.com/line-length.html

**Comment by tuck1s** [comment]
Ah OK, thanks. I've added more articles and I see the space on the right is used for related articles, which makes sense.
