### ISSUE TITLE
Add full Open Graph & Twitter Cards support

### ISSUE THREAD

**Issue by dariagrudzien** [theNewDynamic/gohugo-theme-ananke#405]
# Feature Request

It would be great if this theme provided a full [Open Graph](https://ogp.me/) and [Twitter Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards) support, so that if anyone pastes a link to a blog post to social media, it would generate a correct preview of the post. 

Ideally the social media cards should use the background image for the preview (to match what's displayed on the main page), instead of depending on images which are a shared within the post.

## Is your feature request related to a problem?

Yes. If I want to promote my blog posts on social media, I can't make use of automatically generated previews. This impacts social media performance.

## Solution

Add the necessary meta tags to the `<head>` section of the [base partial](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html#L3)

## Additional Context

Example of a website currently using this theme:
<img width="589" alt="Screen Shot 2021-03-15 at 18 46 37" src="https://user-images.githubusercontent.com/27728733/111197579-ecea7180-85be-11eb-97ec-eef23eb9f057.png">

Example of a correctly generated Twitter Card:
![Screenshot 2021-03-10 at 1 30 27](https://user-images.githubusercontent.com/27728733/111197222-836a6300-85be-11eb-9b23-6a685de48fdb.png)

And the [source code](https://tim.blog/2021/03/08/vitalik-buterin-naval-ravikant/) for this example.

**Comment by budparr** [comment]
Hi @dariagrudzien. We use Hugo's built-in Open Graph and Twitter card shortcodes. You can find documentation on them at the Hugo site: https://gohugo.io/templates/internal#open-graph

https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html#L31
