### ISSUE TITLE
Ananke - Header size of image

### ISSUE THREAD

**Issue by toma-b** [theNewDynamic/gohugo-theme-ananke#410]
Hello;

I’m starting with Hugo since 2 weeks, trying some change and import and I stuck on the header frame.
I use Ananke theme and the header size is depending of:
Image Background: featured_image: ‘/images/gohugo-default-sample-hero-image.jpg’
Size of header: description: " […]"
More word in description, more the header will be tall

http://152.228.163.100/ 1 - A tittle and a description and we see part of the image
http://152.228.163.100/cat3 - There are no description, juste a “title” and we do not see the full image (less than page with description, that is how I know that description upscale the size of the header )
http://152.228.163.100/contact/ - A bit of description, we see a lot of the image

The thing that I want is that the header is ALWAYS 100% of the image size.
No matter the size of the image, no matter if there is description or tittle, I want that the header block size of 100% of the image's height. I see 2 solution for that. Put a max height of the header and I resize image  to enter fully in the header or define the header heigh as 100% of the image. That last solution seems better for future update.
That way, I can change the image when I want and the site will always use it at full size. For now I do not like the fact that the header change size and show more or less of the image.

I do not find any way to do that as parameter in my post.md and I’ve search in theme/ananke files but didn’t find some parameters that I can change.

Is someone can help me to do that ?

**Comment by budparr** [comment]
I believe what you want to do is to make a copy of this file in your project: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/site-header.html#L5 and add your changes there. Does that help?

**Comment by toma-b** [comment]
Hello,

This file and line already exist in on my site in /themes/ananke/layouts/partials/site-header.html
I've tried to change it with the option bg-center for exemple and the image will become centered instead of being top left anchored. Proof that this file is correctly used when I create the site.

But that is not what I want to have because this is just some adjustment of the image.
I want to force the header block to have a height according to the image height.
I want that my header looks like that https://i.imgur.com/EmOkqzA.png
That way we can see ALL the picture in the header, not just some portion of it.

For that I see only 2 possibility,
-Modify the header to have a fixed size and I adjust my image to that size when I want to change.
For example, I want to force my header to be 200px high and if tomorrow I change the image by another image I will have to resize my image by myself to 200px high in order to fit correctly in the head block.

or

-Modify the header to have a size defined by the size of the image and thus that its height = height of the image
For example, If in a month, I change my image and I put one 100px high, I want the header to be 100px high. (According to 100% height of my image) If image do 163px height, the header will be 163px height.

I don't found any option to format the header, that is my problem and I don't know read CSS values in all thoses files.

Is my request is more accurate with this explanation ?

**Comment by budparr** [comment]
Right, but to overwrite the behavior of the header you need to make your own copy of that file. How you accomplish it from there is up to you.

**Comment by toma-b** [comment]
The thing is that I don't know what to change ?

**Comment by budparr** [comment]
I think you'd be best off adding something like this:

where the code has `style="background-image: url('{{ $featured_image }}');"`

you could change to: `style="background-image: url('{{ $featured_image }}');height:200px;"` or whatever height you want. Then, of course, you'd need to make your images that size. The reason the size is not fixed now is that there's no way to account for everyone's images.

I'll close for now because this is more of a general coding issue, which my ability to help is limited, but feel free to re-open or start a new issue if you have more theme-specific questions.

**Comment by toma-b** [comment]
DAMN.
I've tried like that bu fogot a ; 
Thank you
