### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by davidski** [theNewDynamic/gohugo-theme-ananke#412]
Thanks for the terrific theme!

The CHANGELOG is only current as of 2.6.1 and the latest release is 2.6.9 as of this writing. Can the generation script be poked to catch this up with the current release? I'm particularly looking for notes on breaking changes between versions, having hit a few warts on a rather heavily customized deployment I'm running.

Thanks again!

**Comment by budparr** [comment]
Good point, @davidski We'll take care of it.

**Comment by davidsneighbour** [comment]
Fixed in 33178c0d498e
