### ISSUE TITLE
How would i change the name and twitter and how would i addd my own link

### ISSUE THREAD

**Issue by realyusufismail** [theNewDynamic/gohugo-theme-ananke#415]
<img width="548" alt="Screenshot 2021-05-27 at 22 29 57" src="https://user-images.githubusercontent.com/67903886/119899502-13237a80-bf3b-11eb-9f8d-a4f0c6b3c702.png">
Hi how would i change that and how would i change this
<img width="108" alt="Screenshot 2021-05-27 at 22 31 35" src="https://user-images.githubusercontent.com/67903886/119899655-4d8d1780-bf3b-11eb-9bff-8db9e185e5ce.png">

<img width="82" alt="Screenshot 2021-05-27 at 22 30 40" src="https://user-images.githubusercontent.com/67903886/119899574-2cc4c200-bf3b-11eb-9819-4599cfee6fe1.png">

**Comment by realyusufismail** [comment]
https://3cn18iev7zetyw.instant.forestry.io

**Comment by budparr** [comment]
All those options are standard Hugo configuration options, so you'll find detailed answers in the Hugo docs, but in short, you can add them to your config file, such as this example: https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/exampleSite/config.toml
