### ISSUE TITLE
add rel="me" attribute option to socials

### ISSUE THREAD

**Issue by jonbonazza** [theNewDynamic/gohugo-theme-ananke#417]
When you add your website to your Mastodon account's profile metadata, it suggests you add a link back to the mastodon profile on the webpage with the `rel="me"` attribute. This allows mastodon to verify the website is affiliated with the account and displays a little flair along with it letting users know as such.

This theme already includes links back to the mastodon profile when configured (both at the top on the header, as well as on the footer), but the links don't include the `rel="me"` attribute. This should be a trivial change and I'm happy to PR it, but my last PR doesn't even seem to have been looked at yet, so I thought I would start with creating an issue.

**Comment by Altonss** [comment]
This would be really great!

**Comment by nemobis** [comment]
Using rel=me is important, inter alia, for verification on Mastodon. That's becoming very mainstream now [for obvious reasons](https://grahamcluley.com/mastodon-what-you-need-to-know-for-your-security-and-privacy/).

The original idea https://microformats.org/wiki/rel-me was that this would be a bidirectional relationship, which implies the rel=me should ideally be only on the canonical about page or mainpage (example: https://github.com/publiccodenet/jekyll-theme/pull/101/files ), but that's not too strict.
