### ISSUE TITLE
Discord social media icon

### ISSUE THREAD

**Issue by jonbonazza** [theNewDynamic/gohugo-theme-ananke#421]
Discord is one of the most popular platforms for creator communities today. It would be nice if this theme supported Discord invite links as an option for a social media icon similar to existing social media icons.

**Comment by DavisWeaver** [comment]
seconded!

**Comment by regisphilibert** [comment]
You can read the comment on https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/func/socials/GetBuiltInServicesDefaults.html and open a PR
