### ISSUE TITLE
function "return" not defined

### ISSUE THREAD

**Issue by siveryt** [theNewDynamic/gohugo-theme-ananke#427]
When I try to start my Hugo server I get this error:
```log
Error: "/home/sivery/hugo/test/themes/ananke/layouts/partials/func/GetFeaturedImage.html:35:1": parse failed: template: partials/func/GetFeaturedImage.html:35: function "return" not defined
```
How can I fix this?

**Comment by budparr** [comment]
Hi @siveryt Do you know what version of Hugo you're running? The minimum version is .64.

**Comment by siveryt** [comment]
I've already fixed the Issue by myself, but thanks for your reply.
I had Hugo installed via the apt package. As it turn it, this package is outdated. So I've installed it again with Go and now it works in the newest Version. Thx
