### ISSUE TITLE
Tags 2.6.8 and 2.6.9 are not prefixed with 'v'

### ISSUE THREAD

**Issue by dsegonds** [theNewDynamic/gohugo-theme-ananke#429]
The last two tags for this repository (2.6.8 and 2.6.9) are not prefixed with 'v' like the previous tags were. I believe that it may have an impact on using the theme directly as a module in Hugo.

**Comment by budparr** [comment]
Thanks, @dsegonds. I changed them. Not 100% sure of the implications of making the change, but I think it just adds new tags to the repo.
