### ISSUE TITLE
Opengraph image

### ISSUE THREAD

**Issue by RoninTech** [theNewDynamic/gohugo-theme-ananke#430]
Currently, even if I have set a featured_image on one of my hugo pages, there is no corresponding "og:image:" meta tag set to help pages shared to social media sites display the correct image.  I have to do a duplicate entry in the pages .md file for the image in array format:

```
featured_image: path_to_image
images:
     path_to_image
```

If I do not add this "images:" array tag, shared pages on FB, twitter etc. appear to be tagged with the thumbnail of the first image on the page rather than the featured image.  I looked at GetFeaturedImage.html in ananke/layouts/partials/func but it appears to be correctly setting the featured image.

Here is the page on my site that I discovered this when I went to share it on FB: https://carryonrtw.com/van-life/east-west-sliding-bed/ .  It now has the appropriate "og:image" meta tag after adding the "images:...." array entry to the pages .md file, even though it already had the same image referenced in the "featured_image" tag.

```
featured_image: 'https://lh3.googleusercontent.com/pw/AM-JKLU4gtymYtIZ6GcqqKZdW4_spKEnBCZeYNXkq8koqJsNoe6Y6hxzBqIRl599-HudzV1QXkZDqJqVr669lCLylYPL5TTwjqvEpTVvz3BpjFF2qM2GLxcVuPDx6VmiFQtXijctvZKi-fg0Jf3_FqGK8eH59A=w1224-h918-no?'
images:
  - 'https://lh3.googleusercontent.com/pw/AM-JKLU4gtymYtIZ6GcqqKZdW4_spKEnBCZeYNXkq8koqJsNoe6Y6hxzBqIRl599-HudzV1QXkZDqJqVr669lCLylYPL5TTwjqvEpTVvz3BpjFF2qM2GLxcVuPDx6VmiFQtXijctvZKi-fg0Jf3_FqGK8eH59A=w1224-h918-no?'
```

Am I missing something or do I have to make 2 image entries in all of my .md files?

Thanks!

**Comment by regisphilibert** [comment]
Hi @RoninTech 

> Am I missing something or do I have to make 2 image entries in all of my .md files?

You do. The theme relies on Hugo's own built [opengraph tempalte](https://gohugo.io/templates/internal/#open-graph)

**Comment by melroy89** [comment]
Hm.. too bad still.
