### ISSUE TITLE
Chinese text and picture adaptive

### ISSUE THREAD

**Issue by chuxinyuan** [theNewDynamic/gohugo-theme-ananke#432]
When the article is in Chinese, the preview text and pictures are not adaptive, but the English article is.

![](https://rbind.gitee.io/img/20210821111007.png)

**Comment by ppcola** [comment]
Reference from:   https://github.com/theNewDynamic/gohugo-theme-ananke/issues/337#issuecomment-686663652

 set `hasCJKLanguage`  to true in your config

![20210524225608518](https://user-images.githubusercontent.com/76550289/130784678-1ec30d91-edd3-4a81-ba74-2b46d24aec99.png)

After👇

![屏幕截图 2021-08-25 194618](https://user-images.githubusercontent.com/76550289/130785096-ad5f465a-da46-404b-9651-1c83c120a3c7.png)

**Comment by chuxinyuan** [comment]
@ppcola 我这边设置这个参数以后走向了另一个极端，每篇文章就显示一行，有图的左边是图，右边是两行，大概也就相当于没图时候的一行的字数，不知道哪里设置显示字数参数。
