### ISSUE TITLE
Header Image will be darker than original image

### ISSUE THREAD

**Issue by inexcitus** [theNewDynamic/gohugo-theme-ananke#434]
Hello,

I have uploaded a new background image for the header. However, the image is darker than my original image. How can I disable this or is this a bug?
I am hosting my website on Netlify, I don't think that this is the issue. The original Gargoyle image also seems to be brigther than the one on the example page.

Is there any way to disable the "overlay" color?

Regards,
Sascha

**Comment by RoninTech** [comment]
Good question.  I've noticed that all of my hugo ananke page header images are duller than the originals.

**Comment by jcmoraisjr** [comment]
This is like that because of the text on top of the image. You can customize the default css adding a file `static/css/custom.css` with this content:

```
.bg-black-60 {
    background-color: rgba(0,0,0,0.2);
}
```

Last value changes the transparency, default is `0.6`, change to `0` (zero) to make it 100% transparent.

**Comment by regisphilibert** [comment]
I don't think there anything to be done here.
