### ISSUE TITLE
Featured Images don't load when deploying using netlify (even the example site)

### ISSUE THREAD

**Issue by DavisWeaver** [theNewDynamic/gohugo-theme-ananke#450]
A site that I have been working on deploys perfectly when using a local hugo-server. When I publish it using netlify - none of the featured images load. I reproduced this problem using the example site that comes with the theme. 

See the deployed reprex here - https://xenodochial-joliot-02f827.netlify.app/. 
My github repository: https://github.com/DavisWeaver/test_website
I just used all the most basic hugo build settings for the reprex but I tested quite a few different hugo versions with my actual site and couldn't get it to deploy properly. 

![image](https://user-images.githubusercontent.com/20169425/144102393-acf20ae7-1000-413a-8d65-62339562423b.png)

**Comment by budparr** [comment]
Try changing your BaseURL to the actual domain: https://github.com/DavisWeaver/test_website/blob/main/config.toml#L2

**Comment by DavisWeaver** [comment]
That did it! wow. As an old colleague used to say - "The bug is between the keyboard and the chair"
