### ISSUE TITLE
figure shortcode respects height, but ignores width

### ISSUE THREAD

**Issue by tlindsay42** [theNewDynamic/gohugo-theme-ananke#451]
figure shortcode respects height value, but ignores width

Example:

```
{{< figure src="/images/avatars/bio-photo.jpg" alt="Troy Lindsay headshot" height="50" width="50" >}}
```

![image](https://user-images.githubusercontent.com/11078689/144171143-d9914db3-03fb-48f1-aa62-2bff6e4290a0.png)

### Hugo version

```text
hugo version
hugo v0.89.4-AB01BA6E+extended windows/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
```

### Ananke at latest

```powershell
PS C:\Hugo\sites\blog\themes\ananke> git log
commit 3710f7e92a02438ae8508554c0d7a9ea763cc6ba (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by budparr** [comment]
Hey, @tlindsay42 That shortcode is a Hugo built-in, so any issue with it should be reported in the Hugo repo.

Thanks!

I'll close for now, but If I'm missing something here, feel free to re-open.
