### ISSUE TITLE
fail to clone

### ISSUE THREAD

**Issue by ghost** [theNewDynamic/gohugo-theme-ananke#471]
The objective is to deploy this theme on Github pages. But, when the following error pups up in the actions. Any idea?

`clone of 'https://github.com/theNewDynamic/gohugo-theme-ananke.git' into submodule path '...' failed`

**Comment by regisphilibert** [comment]
Have you tried using [Hugo Module](https://github.com/theNewDynamic/gohugo-theme-ananke#as-a-hugo-module-recommended) to setup the theme?

**Comment by chefren** [comment]
Followed the quick start and github deploy steps and it works now.
eg: https://github.com/chefren/chefren.github.io

**Comment by jmooring** [comment]
This can be closed.

**Comment by davidsneighbour** [comment]
@jmooring thank you!
