### ISSUE TITLE
GetFeaturedImage return value always converted to absURL

### ISSUE THREAD

**Issue by tlindsay42** [theNewDynamic/gohugo-theme-ananke#475]
The relative URL returned from the GetFeaturedImage partial is always converted to an absolute URL. Updating the GetFeaturedImage partial to return the absolute URL would reduce repetition.

**Comment by regisphilibert** [comment]
> The relative URL returned from the GetFeaturedImage partial is always converted to an absolute URL

You're right, but I don't think it should. The only time we need an absolute URL is in the SEO tags. Other than that I feel like it should always be relative.

**Comment by regisphilibert** [comment]
Close for #514
