### ISSUE TITLE
A better TOC area

### ISSUE THREAD

**Issue by peter-jerry-ye** [theNewDynamic/gohugo-theme-ananke#478]
Hello,

I'm wondering if we can have a better TOC area, which means the following features:
- the ability to disable "related"
- make text area larger when "related" & "toc" are both disabled
- make toc sticky

Of course these are just my personal opinion. Thank you.

**Comment by budparr** [comment]
Hey, @peter-jerry-ye These shouldn't be too hard for you to change on your local install by adding the single [template](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/single.html) to your install's layout folder, thus [overriding](https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules-with-theme) ours. I'll close for now, but feel free to re-open if you have questions.
