### ISSUE TITLE
Regression in behavior for site-wide featured_images?

### ISSUE THREAD

**Issue by amarburg** [theNewDynamic/gohugo-theme-ananke#489]
We have a site where we define a site-wide `featured_image` in the `config.toml`

```
[params]
  featured_image = "/images/header_image.jpg"
```

After updating to module `gohugo-theme-ananke@v0.0.0-20220110202414-3789b8edae1b`, our default image (on all pages where a featured image is not otherwise called out) no longer appears -- we have a black background instead.

The change introduced by 3789b8e points to `func/GetFeatureImage.html`, which looks for the `featured_image` parameter as `.Params.featured_image` which apparently only looks to the Page params, not the sitewide params?   Is this the expected behavior?

I should note this is a relatively old page, so perhaps we are not following best practices.

**Comment by tlindsay42** [comment]
Darn. I accidentally caused this with #474. Working on a quick PR to fix it.
