### ISSUE TITLE
Posting dates not shown on taxonomy list and term

### ISSUE THREAD

**Issue by yoshi114** [theNewDynamic/gohugo-theme-ananke#496]
The posting dates are not shown (displayed as "Post") on the taxonomy list and term page.

This can be confirmed on the demo site, too:
https://gohugo-ananke-theme-demo.netlify.app/tags/
https://gohugo-ananke-theme-demo.netlify.app/tags/scene/
![image](https://user-images.githubusercontent.com/97032439/149681291-c54c5017-f9b5-40d1-894e-b12d0c5d7988.png)

**Comment by budparr** [comment]
Thanks for reporting, @yoshi114 !
