### ISSUE TITLE
Error in html with params.ananke_socials = "twitter"

### ISSUE THREAD

**Issue by harri00413** [theNewDynamic/gohugo-theme-ananke#505]
Put my url in config.toml and set params.ananke_socials to name: "twitter". 

The resulting html in the svg of the icon contains `{{ .fill }}` and a semi-colon in the style of the `new-window` class : `fill:;`.

**Comment by regisphilibert** [comment]
Thanks for this, we have a release coming up to day, this will be addressed by it.
