### ISSUE TITLE
Investigate switching from `_internal/google_analytics_async.html` to `_internal/google_analytics.html`

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/gohugo-theme-ananke#546]
According to [Hugo Doc](https://gohugo.io/templates/internal#use-the-google-analytics-template), we should probably use `_internal/google_analytics` which supports G4.

I have yet to understand the consequences of such a switch.

**Comment by budparr** [comment]
very bad idea to not use async

**Comment by Aweponken** [comment]
> very bad idea to not use async

Could you elaborate a bit more on this comment @budparr?

**Comment by budparr** [comment]
Perhaps I'm missing something about the loading of G4, but unless it's loaded async automatically, I would never load a blocking script (except for certain, typically rare instances).
