### ISSUE TITLE
Featured Image Fails to Display

### ISSUE THREAD

**Issue by stefano-tronci** [theNewDynamic/gohugo-theme-ananke#549]
Hi! I have been searching online as well as through these issues but I found no solution yet.

Basically, I have a little blog using this theme: https://gitlab.com/stefano-tronci/website
It is deployed here: https://stefano-tronci.gitlab.io/website/

As you can see, the home page does not display the featured image. This is puzzling, because the post displays it correctly. What is more puzzling is that I have a very similar website that works properly: 

* https://gitlab.com/computational-acoustics/website
* https://computational-acoustics.gitlab.io/website

The two websites are pretty much a copy of each other.

Any idea why the featured image doesn't seem to work on the first website?

**Comment by budparr** [comment]
Hi @stefano-tronci Have a look at the example site. It looks like you don't have a `_index...` in your repo. Here's an example https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/exampleSite/content/en/_index.md

**Comment by regisphilibert** [comment]
Hi @stefano-tronci did this solve your problem?

**Comment by stefano-tronci** [comment]
Hey there, thank you for your suggestion! Unfortunately I haven't got a
chance to test it. I think I will test it tonight (UK time).

**Comment by stefano-tronci** [comment]
Yep! That was it. Adding the `_index.md` fixed it. Thank you for your help!
