### ISSUE TITLE
Ananke theme - featured images not displayed when baseURL includes subdirectory

### ISSUE THREAD

**Issue by robexley** [theNewDynamic/gohugo-theme-ananke#556]
See the following post on Hugo discussion forum => https://discourse.gohugo.io/t/ananke-theme-featured-images-not-displayed-when-baseurl-includes-subdirectory/38963

--

I am using Hugo v0.100.1+extended installed using homebrew on Mac with the ananke theme. I’ve setup the structure to use page bundles and have images showing correctly when embedded inline in a post. I am struggling with the featured images on post content.

I’m able to display a featured image for pages if the image is in the static/images folder and referenced via an absolute url (i.e. ‘/images/exampleImage.png’)+

but I’m unable to display any featured images stored within the page bundle using a relative url (e.g. ‘exampleImage.png’ or ‘./exampleImage.png’)

This may also be related to the fact that my site is using an additional path element within the baseURL, e.g. baseURL = ‘site.hostname/project’
so when then url is generated when using a relative URL is
“http://localhost:1313/project/project/posts/2022/03/24/exampleImage.png”
note: the duplication of ‘project’ in the generated URL

**Comment by regisphilibert** [comment]
Hi could you share a link to your repo?

Thanks a ton!

**Comment by robexley** [comment]
Hi Regis,
See the following https://discourse.gohugo.io/t/ananke-theme-featured-images-not-displayed-when-baseurl-includes-subdirectory/38963/3?u=robexley
where Joe Mooring created a specific project in his GitHub repo to illustrate the issue.

**Comment by robexley** [comment]
Hi Regis,
Thanks for that. I've checked out the proposed fix on branch '556-featured-bundle-fix' and tested it using the test case provided by @jmooring and also using my original project site. Both work correctly with your fix - good news!
