### ISSUE TITLE
Module "ananke" is not compatible with this Hugo version

### ISSUE THREAD

**Issue by syahnur197** [theNewDynamic/gohugo-theme-ananke#560]
I got this error when I try to deploy my hugo project in vercel. Not sure if this is Hugo's error or Vercel's
![image](https://user-images.githubusercontent.com/18722385/173998087-2aca5cb4-b817-44f4-b668-f9c856056d0d.png)

**Comment by regisphilibert** [comment]
What's the hugo version? Min Hugo version for ananke is `0.84.0`

**Comment by jmooring** [comment]
This can be closed.

I'm not sure what Vercel's default Hugo version is today, but when this issue was created it was 0.58.2. This is a configuration issue, resolved by adding the `HUGO_VERSION` environment variable to the Vercel configuration file (vercel.json), or in the Vercel UI.

**Comment by davidsneighbour** [comment]
@jmooring thank you!

I have Vercel on a list, netlify has a local configuration that sets a hugo version now.
