### ISSUE TITLE
Font classes not applied consistently

### ISSUE THREAD

**Issue by micw** [theNewDynamic/gohugo-theme-ananke#561]
Hello,

I tried to switch to a sans-serif font, so I added
```
params:
  body_classes: "sans-serif"
  post_content_classes: "sans-serif"
```
That works in most places but not everywhere. 

On the article overview, the caption is still serif:
![image](https://user-images.githubusercontent.com/186753/174653183-74d0e936-c162-42db-b889-b8fdadb8149c.png)

Same for the caption in post details:
![image](https://user-images.githubusercontent.com/186753/174653216-6a82f043-704d-4956-8901-9a4b3cc992ed.png)

**Comment by regisphilibert** [comment]
Closed in favor of #573
