### ISSUE TITLE
How can I create content for the second language of my site using hugo command

### ISSUE THREAD

**Issue by 4strodev** [theNewDynamic/gohugo-theme-ananke#563]
I'm making a site that will use english and spanish. English will be the first language of the site. When I use `hugo new <anything>` hugo creates the content insite the english folder. I would like to create the content also for spanish without copying files manually. How can I make content for spanish version only using `hugo new`.

**Comment by budparr** [comment]
Hi, @4strodev. Hugo new is directory specific, so you have to put the content where you want it: https://gohugo.io/content-management/multilingual/#translate-your-content
