### ISSUE TITLE
How to use https for featured image?

### ISSUE THREAD

**Issue by pietrodito** [theNewDynamic/gohugo-theme-ananke#571]
I have set this up in `content/_index.md`:
```
cascade:                                                                                                                                                       
  featured_image: 'image/welcome.jpg'
```

I get that message in firefox:

`Parts of this page are not secure (as images)`

And when I look at the html source code of the index page I see:
```
<header class="cover bg-top" style="background-image: url('http://www.-------.fr/image/welcome.jpg');">
```
Would it be possible to get those links in https?

**Comment by jhenstridge** [comment]
Is the `baseURL` in your site configuration an http URI, by any chance?

**Comment by pietrodito** [comment]
You are right! My bad...
