### ISSUE TITLE
Page title is output twice when featured image is used

### ISSUE THREAD

**Issue by MxGeMo** [theNewDynamic/gohugo-theme-ananke#578]
When I use <b>featured image</b>, then the <b>page title</b> is output twice.
![2022-10-06_08h02_21](https://user-images.githubusercontent.com/42710284/194227298-3bdd942e-c3da-49b2-88d8-ff219caed3ff.png)

The reason is a different handling in <b>\themes\ananke\layouts\partials\page-header.html</b> when <b>featured image</b> is defined:
![2022-10-06_07h44_37](https://user-images.githubusercontent.com/42710284/194224104-6f1eb035-c3b7-405d-b5e6-b0f81f94742d.png)

I could suppress this double <b>page title</b> when I add an own single.html in <b>\layouts\page\single.html</b>
![2022-10-06_07h51_57](https://user-images.githubusercontent.com/42710284/194224947-aba02ceb-c189-49a2-a372-acc0d197fedb.png)
but so I do not participate on future updates of the official theme for the single.html.

But would it not better to make this adjustments in <b>\themes\ananke\layouts\page\single.html</b>

**Comment by regisphilibert** [comment]
Hi @MxGeMo there is a param called `omit_header_text` this ensures the hero image does not have any text in it. With this, no more duplication.

By, without `omit_header_text`, the title will always appear twice, but but since #585, it will always have only one `h1`
