### ISSUE TITLE
Mastodon verification

### ISSUE THREAD

**Issue by RJGhugo** [theNewDynamic/gohugo-theme-ananke#592]
To show the mastodon icon, I can set the following parameter in the config.toml:

[params]
mastodon = "https://social.example.com/@username"

To use the verify possibilty of mastadon the generated link must have a rel="me".

Please add this to the code.

More about the: [verification process](https://docs.joinmastodon.org/user/profile/#verification).

**Comment by regisphilibert** [comment]
Close in favor of #417
