### ISSUE TITLE
Pagination does not  show which page is currently turned to.

### ISSUE THREAD

**Issue by Pathsis** [theNewDynamic/gohugo-theme-ananke#612]
The pagination of `list.html` does not allow the reader to see which page is currently turned to.

<img width="566" alt="截屏2023-01-30 02 24 05" src="https://user-images.githubusercontent.com/72077265/215347809-c311467e-d62f-4ccc-8545-eabf8de806f5.png">

Like this in Github: 

<img width="595" alt="截屏2023-01-30 02 32 40" src="https://user-images.githubusercontent.com/72077265/215348257-aa039e34-05dc-436e-9085-a8013e7983c8.png">

**Comment by Pathsis** [comment]
I was wrong, there is no such problem.

<img width="371" alt="截屏2023-01-30 02 40 49" src="https://user-images.githubusercontent.com/72077265/215348537-3a2ee062-fe3f-4f1d-bd06-3ddbda5970b5.png">

**Comment by Pathsis** [comment]
Sometimes problems do arise.

**Comment by regisphilibert** [comment]
Have you managed to isolate this issue? The theme is relying on the `_internal/pagination` template so it might be an upstream issue, but I'd love to take a look if possible.

**Comment by Pathsis** [comment]
Thank you for your reply! I can find this problem on the official demo. But I don't know exactly what's happening, I don't know much about programming.

<img width="1735" alt="截屏2023-02-04 00 46 07" src="https://user-images.githubusercontent.com/72077265/216659767-ace0a28e-2ac6-4622-a161-65cb8c235892.png">
