### ISSUE TITLE
hugo -e production not working

### ISSUE THREAD

**Issue by melroy89** [theNewDynamic/gohugo-theme-ananke#625]
When I run `hugo -e production` I expect that there will be a Hugo production build.

However, `hugo -e production` is NOT building the production build?? The only way to get it working is to set `HUGO_ENV` environment variable to `production`. But again, the `hugo -e production` should do the same thing.

See also: https://gohugo.io/hugo-pipes/postprocess/#hugo-environment-variables-available-in-postcss

**Comment by jhenstridge** [comment]
I'd previously reported this in #574, which was closed. There is some discussion there about what needs to change, and why they decided not to do so.
