### ISSUE TITLE
Command Error of Theme: failed to load modules

### ISSUE THREAD

**Issue by AkarinLiu** [theNewDynamic/gohugo-theme-ananke#642]
Error: command error: failed to load modules: module "gohugo-theme-ananke" not found in "C:\\Users\\Scott\\Desktop\\akarinwrt.github.io\\themes\\gohugo-theme-ananke"; either add it as a Hugo Module or store it in "C:\\Users\\Scott\\Desktop\\akarinwrt.github.io\\themes".: module does not exist

**Comment by ajone123** [comment]
I am having a similar error message. 
 
Error: failed to load modules: module "github.com/theNewDynamic/gohugo-theme-Ananke" not found in "C:\\Users\\RENAE\\quickstart\\themes\\github.com\\theNewDynamic\\gohugo-theme-ananke"; either add it as a Hugo Module or store it in "C:\\Users\\RENAE\\quickstart\\themes".: module does not exist,

Solutions attempted to Fix problem: 
C:\Users\RENAE \quickstart> hugo mod get https://github.com/theNewDynamic/gohugo-theme-ananke.git

2nd option: download the theme files extract all inside the themes folder. 

none of the above options worke.

**Comment by amar-sanakal** [comment]
I have the same problem with:
`hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke`

**Comment by amar-sanakal** [comment]
My issue got resolved after I removed the `latest` reference on the `hugo_extended` docker image and replaced it with a `0.100.0` tag

**Comment by Lsm-CVX** [comment]
I got the same error : 

laurent@invidious:~/anatorque2$ hugo mod get -u ./...
laurent@invidious:~/anatorque2$ hugo mod tidy
Error: failed to load modules: module "github.com/theNewDynamic/gohugo-theme-ananke/v2" not found in "/home/laurent/anatorque2/themes/github.com/theNewDynamic/gohugo-theme-ananke/v2"; either add it as a Hugo Module or store it in "/home/laurent/anatorque2/themes".: module does not exist

linux / hugo : 

laurent@invidious:~/anatorque2$ hugo version
hugo v0.131.0+extended linux/amd64 BuildDate=2024-09-03T01:15:37Z VendorInfo=debian:0.131.0-1

Base debian

Tested also : laurent@invidious:~/anatorque2$ hugo mod get -u github.com/theNewDynamic/gohugo-theme-ananke
Error: failed to load modules: module "github.com/theNewDynamic/gohugo-theme-ananke/v2" not found in "/home/laurent/anatorque2/themes/github.com/theNewDynamic/gohugo-theme-ananke/v2"; either add it as a Hugo Module or store it in "/home/laurent/anatorque2/themes".: module does not exist
