### ISSUE TITLE
adding new service svg icon not updated when theme is added as git submodule

### ISSUE THREAD

**Issue by leonieke** [theNewDynamic/gohugo-theme-ananke#647]
I'm hopefully not missing some very simple trick, but when I want to add an unknown service to the [params.ananke_socials], the icon.svg should be added to assets/ananke/socials (from: https://github.com/theNewDynamic/gohugo-theme-ananke#complement)

I have added the theme as a git submodule, and any icon I add myself locally to the theme will not be added when the changes are pushed to my site.

Does anyone have any ideas on how I can fix this?

Thanks!

site: https://leonieke.eu/

**Comment by RoninTech** [comment]
Where exactly did you put the new svg icons and what are their names?  Do you have a repo we can look at?

**Comment by leonieke** [comment]
repo: https://gitlab.com/leonieke/hugo-leonieke/-/tree/master

The icons have the service.svg name, and I added them to the local ananke theme. Have a feeling I'm missing a step, so any help is appreciated.

**Comment by RoninTech** [comment]
Make sure the service.svg files are in assets/ananke/socials, not themes/ananke/assets/ananke/socials.

**Comment by leonieke** [comment]
Thanks so much, fixed my problem!
