### ISSUE TITLE
Contribution: fix hard-coded link to section

### ISSUE THREAD

**Issue by Blackstareye** [theNewDynamic/gohugo-theme-ananke#664]
https://github.com/theNewDynamic/gohugo-theme-ananke/blob/c086834f0ebfa39b8b6b0cfed010588a6907a91c/layouts/index.html#L13C31-L13C31

At the moment, only the first mainsection will be shown in the index.

I changed it so that the mainsections will be iterated with "range $mainsections".
This allows that multiple sections are possible and can be displayed. 

I will link this issue in the PR

![grafik](https://github.com/theNewDynamic/gohugo-theme-ananke/assets/33430997/378e93c1-6387-4de9-b148-a0dac5d3db10)

**Comment by ramiro** [comment]
Shouldn't this issue be closed as fixed?

**Comment by Blackstareye** [comment]
yes
