### ISSUE TITLE
Bad link to demo site

### ISSUE THREAD

**Issue by asayler** [theNewDynamic/gohugo-theme-ananke#688]
The link to the demo site in the README points to `https://gohugo-ananke-theme-demo.netlify.com/` which loads a "Site Not Found" error. The correct link appears to be `https://gohugo-ananke-theme-demo.netlify.app/`. I'll submit a PR to address this shortly.

**Comment by AveryVeilfaire** [comment]
This, again.

**Comment by davidsneighbour** [comment]
This was recently fixed.
