### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by sihemom** [theNewDynamic/gohugo-theme-ananke#692]
Hi dear collaborators!

This Theme looks amazing https://gohugo-ananke-theme-demo.netlify.com/ but The Demo doesn't work. 
Could you please fix it?
Thank you in Advance

**Comment by cscolt** [comment]
https://gohugo-ananke-theme-demo.netlify.app/
Correct site was in a previous or

Trevor Fulham

818.271.8997
Please consider the environment before printing this e-mail

**Comment by baditaflorin** [comment]
The github link still points o the old website.

**Comment by baditaflorin** [comment]
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/61bfd122-da10-4ad4-bb6b-262311c8df48">

**Comment by davidsneighbour** [comment]
Thank you for your reminders. I fixed it some days ago.
