### ISSUE TITLE
Make header opacity configurable

### ISSUE THREAD

**Issue by micw** [theNewDynamic/gohugo-theme-ananke#696]
The background in page-header has a fixed "bg-black-40" class. It would be nice if that can be configured via variable

**Comment by micw** [comment]
Should it use a new parameter or just add the behavior using the existing param?

**Comment by davidsneighbour** [comment]
I am afraid, commenting on a closed issue won't bring much help. We have a [discussion forum for support requests](https://github.com/theNewDynamic/gohugo-theme-ananke/discussions/categories/2-q-a-support). Open a discussion with a proper example of what you try, what you expect, what really happens, and somebody will help you. Looking at the code of this 1-year-old change, it needs to be something along the lines of `bg-black-60` to work, not the colour value itself. `bg` for background (you want to have the background opaque), then the colour name, then a value dividable by 10 for the opacity (0 = transparent, 100 = opaque).

**Comment by LaurieSavage** [comment]
Thank you for your help, I'll fiddle with my custom css.

> I am afraid, commenting on a closed issue won't bring much help. We have a [discussion forum for support requests]
