### ISSUE TITLE
DEMO site is not working

### ISSUE THREAD

**Issue by pcav** [theNewDynamic/gohugo-theme-ananke#709]
https://gohugo-ananke-theme-demo.netlify.com/
from 
https://github.com/theNewDynamic/gohugo-theme-ananke?tab=readme-ov-file
thanks

**Comment by mayuxi** [comment]
+1 [Demo site](https://gohugo-ananke-theme-demo.netlify.com/) gives 

> Site Not Found
> Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.

Please fix!

**Comment by mayuxi** [comment]
@pcav  For some reason, this link seems to be working: https://gohugo-ananke-theme-demo.netlify.app/
it's the **.app** extension, not _.com_

**Comment by pcav** [comment]
I confirm. No idea what was wrong. Thanks, and sorry for the noise.
