### ISSUE TITLE
WARN  deprecated: resources.ToCSS

### ISSUE THREAD

**Issue by henry63** [theNewDynamic/gohugo-theme-ananke#712]
My project causes me this issue :
`WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.`

The only occurence I found of resources.ToCSS are in ananke : 
```
ananke %  find . -type file -exec fgrep -iH "resources.ToCSS" {} \;
./layouts/partials/func/style/GetMainCSS.html:          {{ $assets_to_concat = $assets_to_concat | append (. | resources.ToCSS) }}
./layouts/partials/func/style/GetMainCSS.html:  {{ $style = $style | resources.ToCSS $options | minify }}
```

My project theme in hugo.toml :  `theme = [ "ananke", "hugo-shortcode-gallery"]`

**Comment by gavox** [comment]
Hello!

I understand that this issue was solved, but I still find the same warning when I run my code. 

Is it possible that I do not have the latest version? how can I upgrade?

Thanks
