### ISSUE TITLE
.Site.DisqusShortname error

### ISSUE THREAD

**Issue by tjfinney** [theNewDynamic/gohugo-theme-ananke#714]
Running `hugo server` produces this error:

```
ERROR deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.Disqus.Shortname instead.
```

**Comment by davidsneighbour** [comment]
Hi @tjfinney, this was fixed [10 months ago](https://github.com/theNewDynamic/gohugo-theme-ananke/commit/91df000ca82769a7578df81fa142d1a18e446bc0). Please update your theme integration. If you have problems doing that feel free to use the [Discussions Section](https://github.com/theNewDynamic/gohugo-theme-ananke/discussions) to get help.
