### ISSUE TITLE
bug: ###README and Documentation on themes site mix TOML and YAML syntax

### ISSUE THREAD

**Issue by djotaku** [theNewDynamic/gohugo-theme-ananke#735]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

The README.md has a mix of TOML and YAML syntax that might make it very confusing for someone trying to follow along to edit their configs. 

eg: https://github.com/theNewDynamic/gohugo-theme-ananke#social-follow--share is YAML syntax but https://github.com/theNewDynamic/gohugo-theme-ananke?tab=readme-ov-file#update-font-or-body-classes is TOML syntax

## Expected Behavior

The README.md and documentation should be consistent so someone can follow along, especially newbies.

## Current Behavior

A mix as stated above.

## Possible Solution

Pick one or the other and be consistent. Don't know if there's one way or another that's more de rigeour nowadays with Hugo, but since your config file from the example site is TOML, I suggest making everything TOML.

## Context (Environment)

As I've come online with Hugo, this has been a little bit of an extra confusion.

**Comment by davidsneighbour** [comment]
True. In my own projects I am using mostly three-tabbed displays of all three config formats (toml/yaml/json). That might be possible in the test-website. Not sure if in Github. We probably have to find a consistent config language and then link to converters for convenience for the other two.
