### ISSUE TITLE
bug: ### Build failure in Hugo 0.136.2 due to deprecated Site.Social

### ISSUE THREAD

**Issue by cchessnz** [theNewDynamic/gohugo-theme-ananke#747]
Error message received during a Hugo build of a project using Ananke as theme:

`ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.`

Using Hugo 0.135.0, this was a warning, but in Hugo 0.136.2 it is an error by default.

The error is triggered by `layouts/partials/social-share.html` line `{{ with site.Social.twitter }}`

I found that changing the above text to `site.Params.Social.twitter` made the error go away, but am not sure if that is a correct solution or not.

The effect of this is that I have to run under Hugo 0.135.0 on my Azure SWA deployment, instead of my local dev box's 0.136.2 installation .

**Comment by cchessnz** [comment]
Since the update, I get new icons for FB, Bluesky and LinkedIn on my nav bar, which link to the profile of a user "&lt;nil&gt;" on each site. Is it possible to disable those if there is not a username configured?  I have tried in `hugo.toml` writing:

    [ananke.social.follow]
    new_window_icon = false
    networks = [
    ]

(based on what's in your update to `exampleSite/config.toml`) but that had no effect.

**Comment by davidsneighbour** [comment]
Yes, the location of that config is a bit complicated. Whenever we talk about "`ananke` in the `params` section" what we mean is under the params in the config. It's explained a bit clearer [here](https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Social-media-network-setup#configuration) but I will make it even more clear over the next days in the readme.

Is your issue solved?
