### ISSUE TITLE
Make text color editable/configurable 

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/gohugo-theme-ananke#75]
For instance, this line has a coded text color and it should be either inherited or configurable
https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/post/single.html#L21

n.b. https://discourse.gohugo.io/t/change-text-color-in-ananke/9740/3

**Comment by denmch** [comment]
Would something like this be acceptable?

    {{ .Site.Params.text_color | default "mid-gray" }}

Where config.toml has something like this?

    [params]
        text_color = "black"

If so, (1) what would be the best name for the parameter, and (2) would a pull request require anything in addition, like documentation? The value of the `text_color` param would be a Tachyons text color class.

Or is there a better way to allow people to customize a color?

**Comment by budparr** [comment]
This is good: `{{ .Site.Params.text_color | default "mid-gray" }}`

This is better, because the parameter can be set globally or on a given page:

`{{ $.Param "text_color" | default "mid-gray" }}`

I've thought about making this more general (allowing more parameters to be set there, but probably simplest to stick with color.

Thanks for bringing up documentation. I think it's best to keep things in-line in the templates.

The colors available via [Tachyons](http://tachyons.io/docs/themes/skins/) should be broad enough for text color. If someone really wanted to change them, they can add a color in `src/css/_styles.css`

**Comment by denmch** [comment]
That is better. I just noticed this is marked milestone 2. Are you you planning to put this into a batch, or is this something you’d accept a pull request for? I want to be helpful and not step on your toes. Thanks!

**Comment by budparr** [comment]
Definitely happy to have a PR! I am working on [2.0](https://github.com/budparr/gohugo-theme-ananke/projects/1) but no reason for this to wait.

**Comment by denmch** [comment]
I had issues with the code breaking on quotes while using that within the class list (unless I switched the outer quotes to single quotes), so I pulled it out into a `with` statement like this:

``` 
{{ with $.Param "text_color" | default "mid-gray" }}
  <div class="nested-copy-line-height lh-copy f4 nested-links nested-img {{ . }}">
{{ end }}
```

Does that work for you, or is there a better way?

**Comment by budparr** [comment]
Hey, @denmch I'm a big fan of the `with` statement, but something seems off. Can you send (or point me to) an example of that content? 

_note to self: and a good reminder to dust off those content unit-tests I've been meaning to use on this_

**Comment by veenavijai** [comment]
I added this in my custom CSS file under static/CSS:

```
.nested-links{
  text-align: justify;
  opacity: 1.0;
  width: 100%;
  height: auto;
  color: black;
  font-size: 1.1em;
}
```
It's probably hack-y but works!
