### ISSUE TITLE
bug: Follow RSS feed no longer works in 2.11.0

### ISSUE THREAD

**Issue by theRAAPster** [theNewDynamic/gohugo-theme-ananke#770]
## Expected Behavior
Adding this in my config.toml should show an RSS button in my site's header that links to /posts/index.xml:

```
[params.ananke.social.follow]
new_windows_icon = true
networks = [
  "rss"
]

[params.ananke.social.rss]
profilelink = "/posts/index.xml"
```

## Current Behavior
No RSS button gets added to the header. Adding the instagram, twitter, linkedin networks immediately add a button for them (even if I don't configure the username).

```
[params.ananke.social.follow]
new_windows_icon = true
networks = [
  "rss",
  "instagram"
]

[params.ananke.social.rss]
profilelink = "/posts/index.xml"
```

## Possible Solution
Unsure

## Steps to Reproduce
1. `% hugo version
hugo v0.136.5+extended darwin/arm64 BuildDate=2024-10-24T12:26:27Z VendorInfo=brew`
2. `% hugo new site testquickstart`
3. `% cd testquickstart`
4. `% git init`
5. `% git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke`
6. `echo "theme = 'ananke'" >> hugo.toml`
7. Add the params.ananke.social.follow params above to hugo.toml. Other networks show up but RSS isn't currently

## Context (Environment)
Would like to have the link to the RSS feed again

**Comment by ramiro** [comment]
Reason for this bug seems to be that the `rss` icon is missing. If you edit `config/_default/params.toml` and set `icon = "slack"` (ar any other) under
```toml
[[ananke.social.networks]]
slug = "rss"
...
```
you will see things work but the icon is wrong, obviously.

It seems there is no RSS icon in the free brands Font Awesome set: https://fontawesome.com/search?q=rss&o=r&m=free

**Comment by theRAAPster** [comment]
Looks like it is recognized that RSS should have "just" a free icon:
[` icon = "rss" # font awesome free icon name `](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/1a8ac5d581a13d1b7d322eb3567258d33a0baa42/config/_default/params.toml#L151)

vs

a brand icon:
[`icon = "instagram" # font awesome brand icon name`](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/1a8ac5d581a13d1b7d322eb3567258d33a0baa42/config/_default/params.toml#L85)

For what it's worth, both of the free only icons, RSS & email(envelope), are missing from `assets/ananke/socials/`. IDK if they are manually managed or if a script needs to be updated to pull them too?

**Comment by davidsneighbour** [comment]
I remember adding the RSS and envelope (for email) icons to the assets. Will fix this. For now, if you have an .svg icon add it to your own `assets/ananke/socials/` directory to override.

**Comment by davidsneighbour** [comment]
envelope is [already in the folder](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/main/assets/ananke/socials/envelope.svg), rss is added in a minute.
