### ISSUE TITLE
bug: bluesky social link doesn't work with just "username"

### ISSUE THREAD

**Issue by LPardue** [theNewDynamic/gohugo-theme-ananke#773]
## Expected Behavior

The documentation at https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Social-media-network-setup#available-networks implies that bluesky should just work. My hugo.toml had the following config

```
[params.ananke.social.bluesky]
  username = "simmervigor"
```

For this link to work, it would need to create a link with the url `https://bsky.app/profile/simmervigor.bsky.social`

## Current Behavior

It created a link with the url `https://bsky.app/profile/simmervigor`, which fails to load in bluesky because its unknown

## Possible Solution

I think this is similar to the mastodon situation described in https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Social-media-network-setup#mastodon. There can be various bluesky instances (PDS) and its going to be hard to guess. I resolved my problem by using a config with an explicit `profilelink` field. Perhaps all that is needed is to update the documentation to highlight this is an issue

```
[params.ananke.social.bluesky]
  username = "simmervigor"
  profilelink  = "https://bsky.app/profile/simmervigor.bsky.social"
```

## Steps to Reproduce

This is no longer reproducible on my website since I resolved the issue. However, its fairly easy to repro

1. Add a [params.ananke.social.bluesky] config with only the `username` field

## The bigger picture (we need context)

hugo v0.135.0-f30603c47f5205e30ef83c70419f57d7eb7175ab+extended linux/amd64 BuildDate=2024-09-27T13:17:08Z VendorInfo=gohugoio

ananke git submodule @ 892eaf2f18a8af63e4c586230332be86d772a26a

**Comment by davidsneighbour** [comment]
Currently, in my understanding of Bluesky, your username is actually `simmervigor.bsky.social`. I think there is a misunderstanding or "mis-naming" of username as in "what we use to login". it should probably be something along the lines of `profilename`. But I agree... as Bluesky is something that will grow like Mastodon instances, it's probably best to just circumvent the issue with the recommendation to use a profilelink setup.

**Comment by LPardue** [comment]
Oh good point.

I'll let you resolve this as you see fit, just wanted to flag it before I forgot.

**Comment by davidsneighbour** [comment]
I added a [note to the documentation](https://github.com/theNewDynamic/gohugo-theme-ananke/wiki/Social-media-network-setup#configuring-networks-with-multiple-hosts). I will go through this whole config topic again when I check the share link setups... I had the feeling that there is more possible than just adding the link.
