### ISSUE TITLE
bug: ananke will always show recent posts on index

### ISSUE THREAD

**Issue by Klaas-** [theNewDynamic/gohugo-theme-ananke#794]
This seems to be a regression, either because of the recent ananke changes or because of changes in hugo.
Setting `recent_posts_number = 0` will no longer disable showing recent posts on index.

I tested a little and I think this is because `{{ $n_posts := $.Param "recent_posts_number" | default 3 }}` will default to 3 if recent_posts_number is 0.

## Expected Behavior
Ability to disable recent posts on index

## Current Behavior
not possible to disable recent posts on index

## Possible Solution
Add a parameter to toggle showing recent posts

## Steps to Reproduce

1. set `recent_posts_number = 0`
2. observe recent posts are still being shown

## The bigger picture (we need context)

<details><summary>Hugo Config</summary>
<p>

</p>
</details>

**Comment by davidsneighbour** [comment]
Ignore my comment ;) I did not look at the PR before commenting, and my comment was focused only on the $.Param issue, which is not related to the PR at all.
