### ISSUE TITLE
Add ability to easily disable featured image

### ISSUE THREAD

**Issue by abh** [theNewDynamic/gohugo-theme-ananke#99]
The documentation says:

> You don't need an image though. The default background color is black, but you can change the color, by changing the default color class in the config.toml file. Choose a background color from any on the Tachyons library site, and preface it with "bg-"

However, since change 7b5196ad18b65ead0ec3157d28aaf3a0b02b0a30 that isn't true. There'll always be a hero image. Outside for the demo I don't the gohugo default sample image makes any sense. For the exampleSite it's defined in the config, so I'd suggest reverting the referenced change.

**Comment by SamirTalwar** [comment]
If you set `featured_image = false`, it won't be defaulted.

This took me a while to figure out. It'd be nice to include it in the documentation.

**Comment by danielsoutar** [comment]
Wait, so you can't have the featured_image as anything else??

**Comment by SeanTAllen** [comment]
I removed this in my overrides when using the theme. It struck me as very odd out of sync with the documentation. It appears that all I did was "revert" 7b5196ad18b65ead0ec3157d28aaf3a0b02b0a30.  Is there a desired fix for this?

**Comment by regisphilibert** [comment]
This is no longer the case
